/*EXPTAB: Business Performance > Expenses shows every expense type: totals per category, all entries with a category filter */
var EXCAT=['Leads','Training','Marketing','Software','Licensing and E&O','Office','Other'],EXF='',EXALL=0;
function bzExp(s,rows){const ex=D.expenses,cmk=new Date().toISOString().slice(0,7),tot=sum(ex,x=>x.amt),mth=sum(ex.filter(x=>mon(x.d)===cmk),x=>x.amt);
 const cats=EXCAT.concat([...new Set(ex.map(x=>x.cat).filter(c=>c&&EXCAT.indexOf(c)<0))]);
 const by=cats.map(c=>{const L=ex.filter(x=>x.cat===c);return{c,n:L.length,t:sum(L,x=>x.amt),m:sum(L.filter(x=>mon(x.d)===cmk),x=>x.amt)}});const mx=Math.max(1,...by.map(r=>r.t));
 const kp=`<div class=g>${kpi('Total Expenses',cu(tot,'$'),ex.length+' entr'+(ex.length===1?'y':'ies'))}${kpi('This Month',cu(mth,'$'),'Since the 1st')}${kpi('Lead Spend',cu(s.lead,'$'),s.leadsN+' leads')}${kpi('Cost per Lead',cu(s.lead/s.leadsN,'$'))}</div>`;
 const cat=`<div class="c ext" style="margin-top:14px"><h4>By Category</h4><div class=sc><table><tr><th>Category</th><th class=n>Total</th><th class=n>Share</th><th class=n>This month</th><th class=n>Entries</th><th></th></tr>${by.map(r=>`<tr class="${r.n?'':'ex0'}"><td><button class=exc onclick="EXF=${r.n?`'${esc(r.c).replace(/'/g,"\\'")}'`:"''"};EXALL=0;go()">${esc(r.c)}</button></td><td class=n><b>${$(r.t)}</b></td><td class=n>${tot?(r.t/tot*100).toFixed(1)+'%':'-'}</td><td class=n>${$(r.m)}</td><td class=n>${r.n}</td><td class=exbw><i class=exb><b style="width:${(r.t/mx*100).toFixed(1)}%"></b></i></td></tr>`).join('')}
  <tr class=extot><td><b>TOTAL</b></td><td class=n><b>${$(tot)}</b></td><td class=n>100%</td><td class=n>${$(mth)}</td><td class=n>${ex.length}</td><td></td></tr></table></div></div>`;
 const ch=`<div class=g2 style="margin-top:14px"><div class=c><h4>Where the Money Goes</h4>${dn(grp(ex,x=>x.cat,x=>x.amt))}</div><div class=c><h4>Cost per Lead by Month</h4>${lc(rows.map(r=>{const n=sum(ex.filter(x=>mon(x.d)===r[0]),x=>x.leads||0);return[r[0].slice(2),n?r[3]/n:0]}))}</div></div>`;
 const F=EXF&&cats.indexOf(EXF)>=0?EXF:'',L=ex.map((x,i)=>[x,i]).filter(([x])=>!F||x.cat===F).sort((a,b)=>String(b[0].d).localeCompare(String(a[0].d))),show=EXALL?L:L.slice(0,25);
 const chips=`<div class=exf><button class="${F?'':'on'}" onclick="EXF='';EXALL=0;go()">All (${ex.length})</button>${by.filter(r=>r.n).map(r=>`<button class="${F===r.c?'on':''}" onclick="EXF='${esc(r.c).replace(/'/g,"\\'")}';EXALL=0;go()">${esc(r.c)} (${r.n})</button>`).join('')}</div>`;
 const list=ex.length?`<h3>${F?esc(F)+' expenses':'All expenses'}</h3>${chips}<div class="c sc"><table><tr><th>Date</th><th>Category</th><th class=n>Amount</th><th class=n>Leads</th><th>Vendor</th><th>Note</th><th></th></tr>${show.map(([x,i])=>`<tr><td>${esc(x.d)}</td><td>${esc(x.cat||'Other')}</td><td class=n>${$(x.amt)}</td><td class=n>${x.cat==='Leads'&&x.leads?x.leads:'-'}</td><td>${esc(x.src||'')}</td><td class=mut>${esc(x.n||'')}</td><td><button class=x title="Delete entry" onclick="del('expenses',${i})">&times;</button></td></tr>`).join('')}</table>
  ${L.length>show.length?`<button class="btn o exmore" onclick="EXALL=1;go()">Show all ${L.length}</button>`:''}</div>`:'<p class=mut style="margin-top:14px">No expenses logged yet. Use + Expense to add one.</p>';
 return kp+cat+ch+list}
