// TEST-ONLY demo data generator (never shipped in the portal). Fake people only: 412-555-xxxx phones, @example.com emails.
// Usage in a page: evaluate(GEN + ';crmGenDemo(n, eventsPerContact, seed)') -> writes straight into the CRM store through the normal API.
function crmGenDemo(n,epc,seed){let sd=seed||7;const r=()=>(sd=(sd*9301+49297)%233280)/233280,ri=(a,b)=>a+Math.floor(r()*(b-a+1)),pk=a=>a[Math.floor(r()*a.length)];
 const FN=['Mary','Robert','Linda','James','Patricia','Michael','Barbara','William','Susan','David','Karen','Richard','Nancy','Joseph','Betty','Thomas','Sandra','Charles','Donna','Daniel','Carol','Mark','Ruth','Paul','Sharon','Grace','Henry','Ellen','Walter','Gloria'];
 const LN=['Jones','Miller','Brown','Wilson','Davis','Moore','Taylor','Anderson','Thomas','Jackson','White','Harris','Martin','Thompson','Garcia','Clark','Lewis','Walker','Hall','Allen','Young','King','Wright','Scott','Green','Baker','Adams','Parker','Hughes','Coleman'];
 const ST=['PA','PA','PA','OH','WV','NY','FL','TX','NC','GA','MI','AZ','CA'],PR=['Final Expense','Final Expense','Mortgage Protection','Term','Whole Life','IUL','Annuity'],SR=['Facebook Leads','Facebook Leads','Live Transfers','Direct Mail','Aged Leads','Referral'];
 const AG=['Austin Vardzel','Nate Johnson','Cole Leckey','John Montini','RJ Noullet','Ayman'],STG=['new','new','contacted','contacted','appt','quoted','applied','issued','client','client','dead'];
 const now=Date.now(),day=864e5,docs={},put=(p,k,v,meta)=>{const d=docs[p]||(docs[p]=Object.assign({},meta));d[k]=v};
 const TX={call:['Left a voicemail introducing myself.','Spoke for 10 minutes about final expense options.','No answer, will try again tomorrow.','Reviewed two quotes, wants to talk with family first.'],text:['Sent an intro text.','Client replied asking about monthly cost.','Sent appointment reminder.'],note:['Husband is a veteran, ask about VA benefits.','Budget is about $60 a month.','Prefers calls after 5 pm.','Has diabetes, controlled with pills.'],email:['Sent quotes from two carriers.']};
 for(let i=0;i<n;i++){const id=1700000000000000+i*1000+ri(0,999),fn=pk(FN),ln=pk(LN),name=fn+' '+ln,st=pk(STG),age=ri(38,79),at=now-ri(1,240)*day,state=pk(ST),prod=pk(PR),src=pk(SR),owner=pk(AG);
  const touched=st!=='new'||r()<.2,lt=touched?now-ri(0,30)*day-ri(0,8)*36e5:0,y=new Date(now).getFullYear()-age;
  const c={id,name,phone:'412-555-'+String(1000+((i*7919)%9000)).padStart(4,'0'),email:(fn+'.'+ln+i).toLowerCase()+'@example.com',age:String(age),dob:y+'-'+String(ri(1,12)).padStart(2,'0')+'-'+String(ri(1,28)).padStart(2,'0'),state,city:pk(['Pittsburgh','Columbus','Charleston','Erie','Akron','Tampa']),street:ri(100,9899)+' '+pk(['Maple St','Oak Ave','Pine Rd','Cedar Ln']),zip:'15'+ri(100,299),phone2:'',
   src,ven:'',cost:src==='Live Transfers'?45:src==='Facebook Leads'?22:src==='Aged Leads'?3:0,rcv:at,prod,ap:prod==='Annuity'?0:ri(6,30)*100,stage:st,sAt:now-ri(0,40)*day,owner,tags:r()<.15?['Hot']:r()<.1?['Spouse']:[],at,by:owner,up:at,ub:owner,dnc:0,sms:r()<.5?at:0,
   info:{marital:pk(['Married','Single','Widowed']),occ:pk(['Retired','Teacher','Nurse','Truck driver']),tobacco:pk(['No','No','Yes']),best:pk(['Mornings','Afternoons','Evenings']),goal:pk(['Cover funeral costs','Pay off the mortgage','Leave something for the grandkids','']),budget:pk(['$50/mo','$80/mo','$120/mo',''])},mb:{},lt,ft:touched?at+ri(2,240)*6e4:0,la:ri(0,4),lo:'',cad:{k:src,s:at,n:0,stop:0}};
  const cb='crmc/'+crmCB(id);put(cb,'c'+id,c,{_k:crmCB(id)});
  if(st!=='dead'&&st!=='client'&&r()<.9){const due=st==='new'?at+5*6e4:now+ri(-6,8)*day+ri(-3,3)*36e5,ty=st==='appt'?'appt':pk(['call','call','fu','text']);const tid='g_'+id+'_0';put('crmt/'+crmCB(id),'t'+tid,{id:tid,c:id,ty,t:ty==='appt'?'Appointment':'Follow-up call',due:st==='appt'?crmSOD()+ri(10,19)*36e5:due,ow:owner,s:'o',at,by:owner,r:'man'},{_k:crmCB(id)})}
  for(let j=0;j<epc;j++){const ty=pk(['call','call','text','note','email']),eat=Math.min(now,at+ri(0,Math.max(1,Math.floor((now-at)/36e5)))*36e5),eid='g'+id.toString(36)+'_'+j,p='crme/'+crmEB(id,eat),mt=crmMeta(p);put(p,'e'+eid,{id:eid,c:id,ty,at:eat,by:owner,t:pk(TX[ty]),o:ty==='call'?pk(['na','vm','int','']):''},mt)}}
 const S=CRM.db&&CRM.db._S;if(S){Object.keys(docs).forEach(p=>{S.docs[p]=Object.assign(S.docs[p]||{},docs[p]);S.ver[p]=++S.n});S.subs.forEach(f=>f())}else{Object.keys(docs).forEach(p=>{CRM.sv[p]=Object.assign(CRM.sv[p]||{},docs[p]);crmApply(p)});crmChanged(1)}
 return Object.keys(docs).length}
