import sys;sys.path.insert(0,'/tmp/claude-0/-home-claude/6e37954b-9c9e-57d7-b212-24d756de5469/scratchpad/agents/crm/tests')
from h import *
with sync_playwright() as p:
    b,ctx=launch(p,(1440,900));errs=[];pg=page(ctx,errs)
    url=wrap(CRM+'/out/portal.html',CRM+'/tmp/w.html')
    open_portal(pg,url,6)
    print('crm',pg.evaluate("[crmOn(),CRM.ready,CRM.live,SYK.indexOf('clients'),SUB['Clients']]"))
    pg.evaluate("toggleRail(false);openTab('Clients')");pg.wait_for_timeout(800)
    pg.fill('#crmqc','Mary Jones 412-555-0102 62 PA final expense facebook');pg.wait_for_timeout(200)
    print('prev',pg.inner_text('#crmcp'))
    pg.press('#crmqc','Enter');pg.wait_for_timeout(800)
    print('n',pg.evaluate("[crmAll().length,CRM.t.size,CRM.e.size,MYCL().length,MYCL()[0]&&JSON.stringify(MYCL()[0]).slice(0,300)]"))
    pg.screenshot(path=CRM+'/tmp/s1.png')
    pg.evaluate("crmSub('Pipeline')");pg.wait_for_timeout(500);pg.screenshot(path=CRM+'/tmp/s2.png')
    pg.evaluate("crmOpen(crmAll()[0].id)");pg.wait_for_timeout(600);pg.screenshot(path=CRM+'/tmp/s3.png',full_page=False)
    pg.evaluate("crmSub('Client Book')");pg.wait_for_timeout(500);pg.screenshot(path=CRM+'/tmp/s4.png')
    pg.evaluate("crmSub('Message Builder')");pg.wait_for_timeout(500);pg.screenshot(path=CRM+'/tmp/s5.png')
    pg.evaluate("openTab('Command Deck')");pg.wait_for_timeout(500)
    print('errs',errs[:8])
    b.close()
