"""End-to-end browser test of the CRM main flows (local mode, owner login). Never prints access codes."""
import sys,os,json,time
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from h import *
PORTAL=os.environ.get('CRM_PORTAL',CRM+'/out/portal.html')
R={'pass':0,'fail':0}
def ok(c,msg):
    R['pass' if c else 'fail']+=1;print(('PASS ' if c else 'FAIL ')+msg,flush=True)
with sync_playwright() as p:
    b,ctx=launch(p,(1440,900));errs=[];pg=page(ctx,errs)
    url=wrap(PORTAL,CRM+'/tmp/w_e2e.html');open_portal(pg,url,6)
    def click(sel):
        pg.evaluate("try{crmUHide()}catch(e){}");pg.wait_for_timeout(320);pg.click(sel)
    ok(pg.evaluate("crmOn()&&CRM.ready&&!CRM.live"),'CRM on, ready, local mode')
    ok(pg.evaluate("SYK.indexOf('clients')<0"),'legacy clients sync detached')
    pg.evaluate("toggleRail(false);openTab('Clients')");pg.wait_for_timeout(400)
    ok(pg.evaluate("SUB['Clients']")=='Today' and pg.is_visible('#crmqc'),'Today is the default sub-tab with quick capture')
    ok('paste your first leads here' in pg.inner_text('#crmv').lower(),'empty state teaches')
    # 1 quick capture -> Today -> call outcome -> next touch scheduled
    pg.fill('#crmqc','Mary Jones 412-555-0102 62 PA final expense facebook');pg.press('#crmqc','Enter');pg.wait_for_timeout(500)
    c=pg.evaluate("(()=>{const c=crmAll()[0];return c&&{id:c.id,name:c.name,phone:c.phone,age:c.age,state:c.state,prod:c.prod,src:c.src,stage:c.stage}})()")
    ok(c and c['name']=='Mary Jones' and c['phone']=='412-555-0102' and c['state']=='PA' and c['prod']=='Final Expense' and c['src']=='Facebook Leads','quick capture parsed and created the lead')
    ok(pg.evaluate("document.activeElement&&document.activeElement.id")=='crmqc','focus back in the capture box')
    ok(pg.locator('.crm-qr').count()==1 and 'new lead' in pg.inner_text('.crm-qr').lower(),'lead is first in the Today queue with a why-now chip')
    ok(pg.evaluate("crmNext(%d).id"%c['id'])=='a_%d_new_0'%c['id'],'speed-to-lead call task created')
    pg.fill('#crmqc','Mary Jones 412-555-0102');pg.press('#crmqc','Enter');pg.wait_for_timeout(300)
    ok('Possible duplicate' in pg.inner_text('#crmcp') and pg.evaluate("crmAll().length")==1,'duplicate warning on capture')
    pg.fill('#crmqc','')
    pg.evaluate("crmCallTap(%d)"%c['id']);pg.wait_for_timeout(300)
    ok(pg.locator('.crm-ob').count()==1,'outcome bar after tapping Call')
    click(".crm-ob button:has-text('No answer')");pg.wait_for_timeout(400)
    n=pg.evaluate("(()=>{const t=crmNext(%d);return t&&{due:t.due,r:t.r,ty:t.ty}})()"%c['id'])
    ok(n and n['r']=='next' and n['due']>time.time()*1000,'no answer -> next attempt scheduled')
    ok(pg.evaluate("crmGet(%d).la===1&&crmGet(%d).ft>0"%(c['id'],c['id'])),'attempt counted and first touch stamped (speed to lead)')
    ok('undo' in pg.inner_text('#crmut').lower(),'undo toast offered')
    # Done + Snooze
    t2=pg.evaluate("crmTask({c:%d,ty:'call',t:'Overdue check',due:Date.now()-2*864e5}).id"%c['id']);pg.evaluate("go()");pg.wait_for_timeout(200)
    ok(pg.evaluate("crmCounts().over")==1,'overdue counter')
    pg.evaluate("crmSnoozeGo('%s',Date.now()+36e5)"%t2);pg.wait_for_timeout(300)
    ok(pg.evaluate("crmCounts().over")==0,'snooze moves it out of overdue')
    pg.evaluate("crmTDone('%s')"%t2);pg.wait_for_timeout(700)
    ok(pg.evaluate("CRM.t.get('%s').s"%t2)=='d','done marks the task done')
    # 2 pipeline drag/drop + stage select
    pg.evaluate("crmSub('Pipeline')");pg.wait_for_timeout(400)
    try:
        pg.drag_and_drop('.crm-card','section.crm-col[data-st="quoted"]');pg.wait_for_timeout(400)
    except Exception as e:print('dnd',str(e)[:120])
    st=pg.evaluate("crmGet(%d).stage"%c['id'])
    if st!='quoted':pg.evaluate("crmStageSel(%d,'quoted')"%c['id']);pg.wait_for_timeout(200);st=pg.evaluate("crmGet(%d).stage"%c['id'])
    ok(st=='quoted','pipeline move to Presented / Quoted')
    ok(pg.evaluate("crmEvents(%d).some(e=>e.ty==='stage'&&e.x&&e.x.to==='quoted')"%c['id']),'stage change logged on the timeline')
    # 3 Client 360 edits
    pg.evaluate("crmOpen(%d)"%c['id']);pg.wait_for_timeout(500)
    ok(pg.is_visible('.crm-360'),'Client 360 opens')
    pg.fill('#crmf_email','mary.jones@example.com');pg.dispatch_event('#crmf_email','change');pg.wait_for_timeout(200)
    pg.select_option('#crmf_info_marital','Widowed');pg.wait_for_timeout(200)
    pg.fill('#crmf_dob','1964-05-02');pg.dispatch_event('#crmf_dob','change');pg.wait_for_timeout(200)
    r=pg.evaluate("(()=>{const c=crmGet(%d);return[c.email,c.info.marital,c.dob,c.age]})()"%c['id'])
    ok(r[0]=='mary.jones@example.com' and r[1]=='Widowed' and r[2]=='1964-05-02' and r[3]==str(pg.evaluate("crmAgeOf({dob:'1964-05-02'})")),'profile edits saved (email, marital, dob -> age)')
    pg.fill('#crmnx','Wants $10,000 to cover funeral costs. Daughter is beneficiary.');click("button:has-text('Save note')");pg.wait_for_timeout(300)
    ok(pg.evaluate("crmEvents(%d).some(e=>e.ty==='note'&&/funeral/.test(e.t))"%c['id']),'note saved to timeline')
    ok(pg.evaluate("MYCL()[0].notes.some(n=>/funeral/.test(n.t))"),'legacy shim shows the note')
    # 4 log a policy with the existing modal -> stage + tasks
    pg.evaluate("crmLogPolicy(%d)"%c['id']);pg.wait_for_timeout(300)
    ok(pg.input_value('#pc')=='Mary Jones' and pg.input_value('#ps')=='Submitted','policy modal prefilled')
    pg.fill('#pa','1188');click("#md button:has-text('Save')");pg.wait_for_timeout(500)
    pol=pg.evaluate("D.policies.filter(p=>p.cl==='Mary Jones').map(p=>[p.crmId,p.st,p.ap])")
    ok(len(pol)==1 and pol[0][0]==c['id'],'policy row linked by crmId')
    ok(pg.evaluate("crmGet(%d).stage"%c['id'])=='applied','Submitted policy -> Applied stage')
    pg.evaluate("setPS(D.policies.findIndex(p=>p.crmId===%d),'Issued')"%c['id']);pg.wait_for_timeout(300);pg.evaluate("crmPolicySweep()");pg.wait_for_timeout(300)
    ok(pg.evaluate("crmGet(%d).stage"%c['id'])=='issued','Issued policy -> Issued / Delivery stage')
    ok(pg.evaluate("crmOpenTasks(%d).some(t=>t.ty==='deliv')"%c['id']),'delivery task created')
    # 5 import CSV with duplicates
    csv="Name,Phone,Age,State,Product,Source\nRobert Miller,412-555-0177,58,OH,Mortgage Protection,Live Transfer\nMary Jones,412-555-0102,62,PA,Final Expense,Facebook\nLinda Brown,412-555-0150,71,FL,Final Expense,Direct Mail\nLinda Brown,412-555-0150,71,FL,Final Expense,Direct Mail\n"
    pg.evaluate("crmSub('Today')");pg.evaluate("t=>crmImport(t,'leads.csv')",csv);pg.wait_for_timeout(400)
    txt=pg.inner_text('#md').lower()
    ok('2 possible duplicates' in txt and 'import 2 leads' in txt,'import preview: 2 new, 2 duplicates flagged')
    click('#crmimgo');pg.wait_for_timeout(600)
    ok(pg.evaluate("crmAll().length")==3,'import created exactly the 2 new leads')
    ok(pg.evaluate("crmAll().filter(c=>c.src==='Live Transfers'&&c.prod==='Mortgage Protection').length")==1,'import mapped source and product')
    # 6 Ctrl-K palette
    pg.keyboard.press('Control+k');pg.wait_for_timeout(200);pg.fill('#cpi','new lead');pg.wait_for_timeout(150)
    ok('New lead' in pg.inner_text('#cpl'),'palette has New lead');pg.keyboard.press('Enter');pg.wait_for_timeout(300)
    ok(pg.is_visible('#crmn_name'),'palette opens the new lead form')
    pg.fill('#crmn_name','Grace Parker');pg.fill('#crmn_phone','4125550133');pg.fill('#crmn_age','67');pg.fill('#crmn_state','WV');click("#md button:has-text('Add lead')");pg.wait_for_timeout(400)
    ok(pg.evaluate("crmAll().some(c=>c.name==='Grace Parker'&&c.phone==='412-555-0133'&&c.state==='WV')"),'new lead form saves')
    pg.keyboard.press('Control+k');pg.wait_for_timeout(200);pg.fill('#cpi','Client: Grace');pg.wait_for_timeout(150);pg.keyboard.press('Enter');pg.wait_for_timeout(400)
    ok(pg.evaluate("SUB['Clients']==='Client Book'&&cid===crmAll().find(c=>c.name==='Grace Parker').id")and pg.is_visible('.crm-360'),'palette client entry opens the 360')
    # 7 alerts (new lead waiting) + 8 Command Deck follow-up queue through the shim
    pg.evaluate("(()=>{const c=crmAll().find(c=>c.name==='Grace Parker');crmPut(c.id,{rcv:Date.now()-9*6e4});scanNow()})()");pg.wait_for_timeout(300)
    ok(pg.evaluate("D.alerts.some(a=>/^crmw-/.test(a.k||'')&&a.t==='New lead waiting')"),'alert: new lead waiting (deterministic key)')
    n1=pg.evaluate("D.alerts.length");pg.evaluate("scanNow()");ok(pg.evaluate("D.alerts.length")==n1,'alerts do not repeat')
    pg.evaluate("openTab('Command Deck')");pg.wait_for_timeout(500)
    dq=pg.evaluate("(()=>{const h=[...document.querySelectorAll('.c h4')].find(x=>/Follow-Up Queue/i.test(x.textContent));return h?h.parentNode.innerText:''})()")
    ok('Mary Jones' in dq or 'Robert Miller' in dq or 'Grace Parker' in dq,'Command Deck follow-up queue lists CRM contacts')
    ok('FOLLOW-UPS DUE' in pg.inner_text('.tk'),'deck ticker still renders')
    pg.evaluate("(()=>{const e=[...document.querySelectorAll('.qr')].find(x=>/Grace Parker|Robert Miller|Mary Jones/.test(x.textContent));if(e)e.click()})()");pg.wait_for_timeout(500)
    ok(pg.evaluate("tab==='Clients'&&SUB['Clients']==='Client Book'")and pg.is_visible('.crm-360'),'deck follow-up click opens that client 360')
    # 9 Message Builder still works and saves into the CRM record
    gid=pg.evaluate("crmAll().find(c=>c.name==='Grace Parker').id")
    pg.evaluate("mbOpen(%d)"%gid);pg.wait_for_timeout(400)
    ok(pg.is_visible('#mbo') and 'Grace Parker' in pg.input_value('#mbo'),'Message Builder opens with the client')
    pg.fill('#mbf_company','Americo');pg.wait_for_timeout(300)
    ok(pg.evaluate("crmGet(%d).mb.company"%gid)=='Americo' and 'Americo' in pg.input_value('#mbo'),'Message Builder field saved to CRM')
    ok(len(pg.evaluate("crmGet(%d).mb.pin||''"%gid))==4,'PIN generated once and stored')
    click("button:has-text('Save to client log')");pg.wait_for_timeout(300)
    ok(pg.evaluate("crmEvents(%d).some(e=>/Message sent/.test(e.t))"%gid),'Message Builder log goes to the timeline')
    # 10 delete + undo
    pg.evaluate("crmSub('Client Book')");pg.evaluate("crmOpen(%d)"%gid);pg.wait_for_timeout(300);pg.evaluate("crmDelAsk(%d)"%gid);pg.wait_for_timeout(200);click('#yes');pg.wait_for_timeout(400)
    ok(pg.evaluate("!crmGet(%d)&&crmAll().length===3"%gid),'delete removes the contact')
    pg.click("#crmut button:has-text('Undo')",force=True);pg.wait_for_timeout(400)
    ok(pg.evaluate("!!crmGet(%d)&&crmAll().length===4"%gid),'undo restores it')
    # 11 legacy write paths
    pg.evaluate("openM('C')");pg.fill('#cn1','Walter Ross');pg.fill('#cp','412-555-0144');pg.fill('#cf','2026-12-01');pg.evaluate("saveC(0)");pg.wait_for_timeout(300)
    w=pg.evaluate("(()=>{const c=crmAll().find(c=>c.name==='Walter Ross');return c&&[c.phone,crmNext(c.id)&&crmDay(crmNext(c.id).due),MYCL().find(x=>x.id===c.id).fu]})()")
    ok(w and w[0]=='412-555-0144' and w[1]=='2026-12-01' and w[2]=='2026-12-01','legacy Add Client routes to the CRM (follow-up date -> task)')
    wid=pg.evaluate("crmAll().find(c=>c.name==='Walter Ross').id")
    pg.evaluate("clearFu(%d)"%wid);pg.wait_for_timeout(200);ok(pg.evaluate("MYCL().find(x=>x.id===%d).fu"%wid)!='2026-12-01','legacy clearFu routes to the CRM')
    pg.evaluate("ciSet(%d,'occ','Electrician')"%wid);ok(pg.evaluate("crmGet(%d).info.occ"%wid)=='Electrician','legacy ciSet routes to the CRM')
    pg.evaluate("crmSimLead()");pg.wait_for_timeout(300);ok(pg.evaluate("crmAll().some(c=>/Inbound lead/.test((crmEvents(c.id)[0]||{}).t||''))"),'simulated inbound lead becomes a CRM contact')
    ok(pg.evaluate("crmDeckStats().newLeads")>=1,'crmDeckStats() available')
    # windowed list sanity
    pg.evaluate("cid=null;crmSub('Client Book')");pg.wait_for_timeout(300);ok(pg.locator('.crm-row').count()==pg.evaluate("CRM.ui.list.length"),'client book lists every contact (small list)')
    pg.fill('#crmbq','walter ross');pg.wait_for_timeout(200);ok(1<=pg.locator('.crm-row').count()<=2 and pg.evaluate("[...document.querySelectorAll('.crm-row')].every(r=>/Walter Ross/.test(r.innerText))"),'search filters the list')
    # reload: local persistence
    pg.evaluate("crmFlush()");pg.wait_for_timeout(600);pg.goto(url);pg.wait_for_timeout(2500);lgx.login(pg,6);pg.wait_for_timeout(1500)
    ok(pg.evaluate("crmAll().length")==6,'local mode persists across reloads (%s contacts)'%pg.evaluate("crmAll().length"))
    print('errors:',errs[:6]);ok(not errs,'no console errors')
    b.close()
print('e2e: %d passed, %d failed'%(R['pass'],R['fail']));sys.exit(1 if R['fail'] else 0)
