/* ---- LOOK B: MISSION CONTROL. Ops-centre wall: live feed, KPI strip, radar, heat strips, a NEEDS ATTENTION column ---- */
function dkFeedB(d){const it=[],fn=n=>esc(String(n||'').split(' ')[0]);
  D.policies.filter(p=>p.d===today&&live(p)).slice(-4).reverse().forEach(p=>it.push(['ok','POLICY ISSUED',esc(p.cl)+' &middot; '+$(p.ap)+' &middot; '+esc(p.ag||'Unassigned')]));
  AL().slice(0,5).forEach(a=>it.push([a.sev,'ALERT',esc(a.t)+' &middot; '+esc(a.m)]));
  try{chAll().slice().sort((a,b)=>b.at-a.at).slice(0,3).forEach(m=>it.push(['info','#'+esc(m.ch),fn(m.who)+': '+esc(String(m.text||'[file]').replace(/\s+/g,' ').slice(0,70))]))}catch(e){}
  if(d.due.length)it.push(['warn','FOLLOW-UPS',d.due.length+' due &middot; oldest '+esc(d.due[0].name)]);
  try{const l=chLive()[0];if(l){const e=chEval(l),r=e.rows[0];it.push(['gold','CHALLENGE',esc(l.name)+(r&&r.val>0?' &middot; leader '+esc(r.nm):'')])}}catch(e){}
  if(!it.length)it.push(['info','STATION','All systems nominal']);
  const row=it.map(x=>`<span class="dk-fi dk-s-${x[0]}"><b>${x[1]}</b>${x[2]}</span>`).join('');
  return`<div class=dk-feed role=region aria-label="Live feed"><b class=dk-fl><i></i>LIVE FEED</b><div class=dk-fw><div class=dk-ft style="--n:${it.length}">${row}<span class=dk-fdup aria-hidden=true>${row}</span></div></div></div>`}
function dkNeedB(d){const L=[];
  d.due.forEach(c=>L.push([c.fu<today?'crit':'gold',c.fu<today?'Overdue follow-up':'Follow-up due today',esc(c.name)+' &middot; '+c.fu,`cid=${c.id};openTab('Clients')`]));
  d.crit.filter(a=>!/follow-up/i.test(a.t)).slice(0,3).forEach(a=>L.push(['crit','Critical alert',esc(a.t)+' &middot; '+esc(a.m),`alGo(${a.id})`]));
  if(d.ck.length)L.push(['warn',d.owner?'No check-in yet today':'Your daily check-in',d.owner?esc(d.ck.map(n=>String(n).split(' ')[0]).join(', ')):'Not sent yet today',`openTab('Check-In')`]);
  try{const s=mrStatus();if(s.st==='wait'||s.st==='late')L.push([s.st==='late'?'crit':'gold','Morning Recognition',(s.w.who?esc(String(s.w.who).split(' ')[0])+' &middot; ':'')+(s.st==='late'?'overdue':'due '+esc(mrClock(mrCfg().dl))),`openTab('Morning Recognition')`])}catch(e){}
  const n=L.length,sh=L.slice(0,8);
  return`<div class="c dk-need"><div class=dk-nh><h4>Needs Attention</h4><em class="dk-nc${n?'':' z'}">${n}</em></div>${sh.map(x=>`<div class="dk-ni dk-s-${x[0]}" tabindex=0 role=button onclick="${x[3]}" onkeydown="if(event.key=='Enter')this.click()"><i aria-hidden=true></i><span><b>${x[1]}</b><small>${x[2]}</small></span><em aria-hidden=true>&#9656;</em></div>`).join('')||'<p class=dk-clear>All clear. Nothing needs you right now.</p>'}${n>sh.length?`<small class=mut>+ ${n-sh.length} more in the queues below</small>`:''}</div>`}
function dkRadarB(d){const R=d.R.filter(r=>r.goal),P=d.P?d.P.ag:[],on=n=>P.some(a=>a.nm===n&&a.on),C=110;
  const bl=R.map((r,i)=>{const p=Math.min(1.08,r.w/r.goal),t=-Math.PI/2+i*2*Math.PI/Math.max(1,R.length),rr=14+p*82,x=C+rr*Math.cos(t),y=C+rr*Math.sin(t),c=p>=1?'ok':p>=.6?'mid':'low';
    return`<g class="dk-bp dk-bp-${c}${on(r.nm)?' on':''}"><circle cx=${x.toFixed(1)} cy=${y.toFixed(1)} r=5 /><text x=${(x+8).toFixed(1)} y=${(y+3.5).toFixed(1)}>${esc(ini(r.nm))}</text></g>`}).join('');
  return`<div class="c dk-radar"><h4>Agent Radar</h4><div class=dk-rdw><svg class=dk-rd0 viewBox="0 0 220 220" aria-hidden=true>${[.25,.5,.75,1].map(v=>`<circle cx=${C} cy=${C} r=${(14+v*82).toFixed(1)} class=dk-rr />`).join('')}<line x1=${C} y1=10 x2=${C} y2=210 class=dk-rx2 /><line x1=10 y1=${C} x2=210 y2=${C} class=dk-rx2 /><text x=${C+3} y=${C-14-41+10} class=dk-rlb>50%</text><text x=${C+3} y=${C-96+10} class=dk-rlb>GOAL</text>${bl}</svg><svg class=dk-rd1 viewBox="0 0 220 220" aria-hidden=true><defs><linearGradient id=dkrsw x1=0 y1=0 x2=1 y2=0><stop offset=0 stop-color="#3ddc97" stop-opacity=0 /><stop offset=1 stop-color="#3ddc97" stop-opacity=.32 /></linearGradient></defs><path d="M${C} ${C} L${C} ${C-98} A98 98 0 0 1 ${(C+98*Math.sin(Math.PI/4)).toFixed(1)} ${(C-98*Math.cos(Math.PI/4)).toFixed(1)} Z" fill="url(#dkrsw)" /></svg></div>
<small class=dk-rleg>Distance from the centre = weekly goal progress. <b class=dk-gdot></b> gold ring = on the clock now.</small></div>`}
function dkHeatB(d){if(!d.heat.length)return'';const mx=Math.max(1,...d.heat.flatMap(h=>h.v)),dl=d.days.map((k,i)=>{const t=new Date(k+'T12:00:00');return{we:t.getDay()===0||t.getDay()===6,t:k===today,lab:i%2===0||k===today?['S','M','T','W','T','F','S'][t.getDay()]+' '+t.getDate():''}});
  return`<div class="c dk-heat"><h4>Activity Heat: Last 14 Days</h4><div class=dk-hg>${d.heat.map(h=>`<div class=dk-hr><b>${esc(String(h.nm).split(' ')[0])}</b><div class=dk-hc>${h.v.map((v,i)=>`<i class="${dl[i].we?'we':''}${dl[i].t?' t':''}" style="--h:${(v/mx).toFixed(2)}" title="${d.days[i]}: ${Math.round(v)}"></i>`).join('')}</div></div>`).join('')}<div class="dk-hr dk-hx"><b></b><div class=dk-hc>${dl.map(x=>`<em>${x.lab}</em>`).join('')}</div></div></div><small class=dk-rleg>Contacts plus appointments logged per day (an appointment counts as 5). Today is outlined in gold.</small></div>`}
function dkLook_b(d,tier){const M=dkMods(d),s=d.s,pa=d.pa,cl=d.cl,ld=cl.filter(x=>x.st=='Lead'||x.st=='Quoted').length,cn=cl.filter(x=>x.st=='Client').length,tot=Math.max(1,cl.length);
  const seg=(p,c)=>`<span class="dk-seg${c?' '+c:''}" aria-hidden=true><i style="width:${Math.max(0,Math.min(100,p*100)).toFixed(1)}%"></i></span>`,sg=v=>(v>=0?'+':'')+$(v);
  const chip=(t,c)=>`<em class="dk-dc${c?' dk-'+c:''}">${t}</em>`;
  const tdy=d.P?d.P.ap:0,mInc=d.inc(cmk),mExp=sum(D.expenses.filter(x=>mon(x.d)===cmk),x=>x.amt),sub=D.policies.filter(p=>p.st==='Submitted').length;
  const gp=Math.max(0,Math.min(1,d.gp||0)),C=60,r=50,c2=2*Math.PI*r,wm=Math.max(1,...d.wk.map(x=>x.v));
  const pace=D.goal?DOM/DIM:0,fcp=D.goal?Math.min(1.25,d.f.proj/D.goal):0,bw=v=>(Math.max(0,Math.min(1.25,v))/1.25*100).toFixed(1)+'%';
  const bullet=`<div class=dk-bul aria-hidden=true><div class=dk-bub><i class=dk-buf style="width:${bw(fcp)}"></i><i class=dk-bum style="width:${bw(gp)}"></i><b class=dk-bup style="left:${bw(pace)}"></b><b class=dk-bug style="left:${bw(1)}"></b></div><div class=dk-bul2><span><i class=dk-l1></i>Issued</span><span><i class=dk-l2></i>Forecast</span><span><i class=dk-l3></i>Pace today</span><span><i class=dk-l4></i>Goal</span></div></div>`;
  const wkT=`<div class="c dk-kpi dk-wk"><h4>This Week</h4><div class=dk-wkb aria-hidden=true>${d.wk.map(x=>`<span class="${x.t?'t':''}${x.fut?' f':''}"><i style="height:${Math.max(x.v?8:2,x.v/wm*100).toFixed(0)}%"></i><em>${x.l}</em></span>`).join('')}</div><small>Issued premium by day: ${$(sum(d.wk,x=>x.v))} so far</small></div>`;
  const netT=`<div class="c dk-kpi dk-net" data-dkburst><h4>Net Profit</h4><div class=dk-nw><svg class=dk-ng viewBox="0 0 120 120" aria-hidden=true><defs><filter id=gl x=-30% y=-30% width=160% height=160%><feGaussianBlur stdDeviation=2.5 result=b /><feMerge><feMergeNode in=b /><feMergeNode in=SourceGraphic /></feMerge></filter><linearGradient id=rg x1=0 y1=0 x2=1 y2=1><stop offset=0 stop-color="#ff1f4f" stop-opacity=.5 /><stop offset=1 stop-color="#ffcf40" /></linearGradient></defs><circle cx=${C} cy=${C} r=${r} class=dk-ngt /><circle cx=${C} cy=${C} r=${r} class=dk-ngv stroke-dasharray="${(c2*gp).toFixed(1)} ${c2.toFixed(1)}" style="--c:${c2.toFixed(1)}" transform="rotate(-90 ${C} ${C})" filter="url(#gl)" /><text x=${C} y=${C+5} class=dk-ngp>${Math.round(gp*100)}%</text></svg><div class=dk-nv><div class=v>${dkN('net',s.net,'$')}</div>${chip(sg(mInc-mExp)+' THIS MONTH',mInc-mExp>=0?'up':'dn')}</div></div>${bullet}<small>${dkGoalTxt(d)}</small></div>`;
  const kpis=`<div class="deck dk-kpis">${netT}`+
    M.sales('dk-kpi',chip('+'+$(tdy)+' TODAY',tdy>0?'up':'')+seg(s.p.length?s.iss.length/s.p.length:0))+
    M.fin('dk-kpi',chip('+'+$(mInc)+' THIS MONTH','up')+seg(s.rev?Math.max(0,s.net/s.rev):0))+
    M.clients('dk-kpi',chip(d.due.length+' FOLLOW-UPS DUE',d.due.length?'warn':'')+`<div class=dk-split aria-hidden=true><i style="width:${(ld/tot*100).toFixed(1)}%"></i><b style="width:${(cn/tot*100).toFixed(1)}%"></b></div>`)+
    M.path('dk-kpi',pa.has?chip(Math.round(pa.hw)+' HRS &middot; '+K(pa.lw)+' LEADS / WK',''):'')+
    `<div class="chips dk-chips"><div class=dk-kpi2><small>HEALTH</small><b>${dkN('health',d.h.score,'n')}</b>${seg(d.h.score/100,'h')}</div><div class=dk-kpi2><small>FORECAST</small><b>${dkN('fc',d.f.proj,'K')}</b>${chip(P(D.goal?d.f.proj/D.goal:0)+' OF GOAL',d.f.proj>=D.goal?'up':'warn')}</div><div class=dk-kpi2><small>PIPELINE</small><b>${dkN('pipe',d.f.pend,'K')}</b>${chip(sub+' SUBMITTED','')}</div></div>${wkT}</div>`;
  return dkHead(d,`<span class=dk-st><i></i>OPS ONLINE &middot; ${d.P?d.P.ag.filter(x=>x.on).length:0} ON THE CLOCK &middot; ${d.unread} UNREAD ALERTS</span>`)+(d.owner?cqHtml():'')+mrBanner()+dkFeedB(d)+kpis+
  `<div class=dk-ops><div class=dk-main>${pulseHtml()}<div class=dk-row2>${dkRadarB(d)}${dkAgents(d,'dk-ag')}</div>${dkHeatB(d)}<div class=dk-row2>${dkBriefCard('dk-br')}${dkDiag(d,'dk-dg')}</div></div>
<div class=dk-side2>${dkNeedB(d)}${dkQueue(d,'dk-q')}${dkAlerts('dk-al')}${mrDeck()}${chDeck()}</div></div>`}
