/* ===== CRM views (crm builder): Today, Pipeline, Client Book + Client 360. ASCII only. ===== */
const CRM_TABS=['Today','Pipeline','Client Book','Message Builder'],CRM_RH=58;
const CRM_OUTS={na:'No answer',vm:'Voicemail',int:'Interested',appt:'Appt set',cb:'Call back',ni:'Not interested',bad:'Wrong number',dnc:'Do not contact'};
const CRM_TXT={new:'Hi {{first}}, this is {{agent}}. You recently asked about {{product}} coverage for your family. Is now a good time for a quick 5-minute call?',
 fu:'Hi {{first}}, {{agent}} here following up on your coverage options. When is a good time to talk today?',
 vm:'Hi {{first}}, {{agent}} here. I just tried calling about the {{product}} information you asked for. Call or text me back whenever it suits you.',
 appt:'Hi {{first}}, this is {{agent}} confirming our appointment {{when}}. Reply YES to confirm or send me a better time.',
 deliv:'Hi {{first}}, great news: your policy was approved! Let us set a quick time to go over it together with your beneficiary.'};
function crmTL(t){const ty=CRM_TY[t.ty]||'Task',x=String(t.t||'');return!x||x===ty?ty:x.indexOf(ty)===0?x:ty+': '+x}
function crmQS(s){return String(s==null?'':s).replace(/[^A-Za-z0-9_\-]/g,'')}
function crmIni(n){const p=String(n||'?').trim().split(/\s+/).filter(Boolean);return(((p[0]||'?')[0]||'?')+(p.length>1?p[p.length-1][0]:'')).toUpperCase()}
function crmAv(c,s){return`<span class=crm-av style="--s:${s||36}px;--h:${crmHash(c.name||c.id)%360}" aria-hidden=true>${esc(crmIni(c.name))}</span>`}
function crmOwnAv(n){return n&&n!=='Unassigned'?`<span class=crm-oa title="Owner: ${esc(n)}">${esc(crmIni(n))}</span>`:'<span class="crm-oa un" title="Unassigned">?</span>'}
function crmFirst(n){return String(n||'').trim().split(/\s+/)[0]||''}
function crmAgo(ts){if(!ts)return'never';const s=Math.max(0,(Date.now()-ts)/1000);return s<60?'just now':s<3600?Math.round(s/60)+'m ago':s<86400?Math.round(s/3600)+'h ago':Math.round(s/86400)+'d ago'}
function crmTime(ts){return new Date(ts).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function crmWhen(ts,ad){const s=crmSOD(),d=crmSOD(ts),dd=Math.round((d-s)/864e5),tm=ad?'':' '+crmTime(ts);if(dd===0)return'Today'+tm;if(dd===1)return'Tomorrow'+tm;if(dd===-1)return'Yesterday'+tm;if(dd>1&&dd<7)return new Date(ts).toLocaleDateString([],{weekday:'short'})+tm;return new Date(ts).toLocaleDateString([],{month:'short',day:'numeric'})+tm}
function crmDigits(p){return String(p||'').replace(/\D/g,'').slice(-10)}
function crmAgentName(c){const o=c&&c.owner;if(o&&o!=='Unassigned'&&o!=='Agency Owner')return o;return WHO==='Agency Owner'?'Cole Leckey':WHO}
function crmFill(tpl,c,t){const m={first:crmFirst(c.name),client:c.name,agent:crmAgentName(c),product:String(c.prod||'life insurance').toLowerCase(),when:t?crmWhen(t.due):''};return String(tpl).replace(/\{\{(\w+)\}\}/g,(a,k)=>k in m?m[k]:a)}
function crmTxtFor(c,t){const k=t&&t.ty==='appt'?'appt':t&&t.ty==='deliv'?'deliv':(c.lo==='vm'||c.lo==='na')?'vm':c.stage==='new'?'new':'fu';return crmFill(((CRM.cfg||{}).txt||{})[k]||CRM_TXT[k],c,t)}
function crmTel(c){const d=crmDigits(c.phone);return d.length===10&&!c.dnc?'tel:+1'+d:''}
function crmSms(c,t){const d=crmDigits(c.phone);return d.length===10&&!c.dnc?'sms:+1'+d+'?&body='+encodeURIComponent(crmTxtFor(c,t)):''}
function crmMail(c){return c.email&&!c.dnc?'mailto:'+encodeURIComponent(c.email)+'?subject='+encodeURIComponent('Your coverage options')+'&body='+encodeURIComponent(crmTxtFor(c,crmNext(c.id))):''}
function crmLink(href,label,cls,on,aria){return href?`<a class="${cls}" href="${esc(href)}" ${on?`onclick="${on}"`:''} aria-label="${esc(aria||label)}">${label}</a>`:`<span class="${cls}" aria-disabled=true title="No number on file">${label}</span>`}
function crmAgents(){const s=new Set((typeof D!=='undefined'?D.agents:[]).map(a=>a.name));return[...s]}
function crmScope(){return crmOwnerView()&&CRM.ui.ag?CRM.ui.ag:WHO}
function crmCan(c){return !!c&&(crmOwnerView()||c.owner===WHO||!c.owner||c.owner==='Unassigned')}
function crmStPill(st){return`<span class="crm-pill st-${crmQS(st)}">${esc(CRM_SN[st]||st)}</span>`}
function crmNum(v){return CRM.ui.quiet?String(v):cu(v,'n')}
/* ---------- shell ---------- */
function crmSyncState(){return!CRM.live?['local','LOCAL ONLY','Saved on this device only']:CRM.ro?['warn','VIEW ONLY',CRM.why||'Changes are not shared']:!CRM.ready?['warn','CONNECTING','Loading the shared CRM']:CRM.err?['crit','SYNC ERROR',CRM.err]:(CRM.q.length||CRM.pump)?['warn','SAVING','Sending changes to the team']:['ok','SHARED','Everyone sees the same CRM']}
function crmSyncChip(){const s=crmSyncState();return`<span class="crm-sy ${s[0]}" title="${esc(s[2])}" role=status><i></i>${s[1]}</span>`}
function crmSyncUI(){const e=document.getElementById('crmsy');if(e)e.innerHTML=crmSyncChip()}
function crmHead(sub){const t={Today:'Who to call, text and meet right now. Everything else waits.',Pipeline:'Every deal by stage. Drag a card to move it.','Client Book':'Every contact with the full history, one tap away.','Message Builder':'Pick a client and get a ready-to-send policy message.'}[sub]||'';
 const due=CRM.ready?crmQueue(crmScope()).length:0;
 return`<div class="hd crm-hd"><div><h2>Clients</h2><p class=mut>${t}</p></div><div class=crm-hb><span id=crmsy>${crmSyncChip()}</span><button class="btn o" onclick="crmImport()">Import</button><button class=btn onclick="crmNewLead()">+ New lead</button></div></div>
<div class="seg crm-tabs" role=tablist aria-label="Clients sections">${CRM_TABS.map(x=>`<button role=tab aria-selected="${x===sub}" class="${x===sub?'on':''}" onclick="crmSub('${x}')">${x}${x==='Today'&&due?`<em class=crm-tb>${due}</em>`:''}</button>`).join('')}</div>`}
function crmSub(x){SUB['Clients']=x;go();const m=document.getElementById('main');if(m)m.scrollTop=0}
function crmView(){try{if(cid!=null&&cid!==CRM.ui.lastCid&&SUB['Clients']!=='Message Builder'&&crmGet(cid))SUB['Clients']='Client Book'}catch(e){}
 CRM.ui.lastCid=typeof cid==='undefined'?null:cid;let sub=SUB['Clients'];if(CRM_TABS.indexOf(sub)<0)sub=SUB['Clients']='Today';
 if(sub==='Message Builder')return msgBuilder();
 setTimeout(crmAfter,0);setTimeout(crmPolicySweep,0);
 return crmHead(sub)+`<div id=crmv class="crm-v crm-s-${crmQS(sub)}">${crmBody(sub)}</div>`}
function crmBody(sub){CRM.ui.rv=CRM.ver;CRM.ui.rsub=sub;if(!CRM.ready)return`<div class="c crm-empty"><h4>Connecting</h4><p>Loading the shared client book. This takes a moment the first time.</p></div>`;
 return sub==='Pipeline'?crmVPipe():sub==='Client Book'?crmVBook():crmVToday()}
function crmRefresh(remote){crmSyncUI();if(!crmOn()||typeof ONLINE==='undefined'||!ONLINE||tab!=='Clients')return;if(CRM.ui.rv===CRM.ver)return;
 if(SUB['Clients']==='Message Builder')return;const md=document.getElementById('md');if(md&&md.innerHTML)return;
 const ae=document.activeElement;if(ae&&/INPUT|TEXTAREA|SELECT/.test(ae.tagName||'')&&ae.closest&&ae.closest('#main'))return;
 const v=document.getElementById('crmv');if(!v){return}const m=document.getElementById('main'),y=m?m.scrollTop:0;
 CRM.ui.quiet=1;try{const sub=SUB['Clients'];v.innerHTML=crmBody(sub);const tb=document.querySelector('.crm-tabs');if(tb){const due=crmQueue(crmScope()).length,b=tb.querySelector('button');if(b)b.innerHTML='Today'+(due?`<em class=crm-tb>${due}</em>`:'')}}finally{CRM.ui.quiet=0}
 if(m)m.scrollTop=y;crmAfter()}
function crmAfter(){const vl=document.getElementById('crmvl');if(vl){if(!vl.dataset.b){vl.dataset.b=1;vl.addEventListener('scroll',()=>{CRM.ui.scroll=vl.scrollTop;if(!CRM.ui.raf){CRM.ui.raf=1;requestAnimationFrame(()=>{CRM.ui.raf=0;crmListPaint()})}},{passive:true})}vl.scrollTop=CRM.ui.scroll||0;crmListPaint()}
 const f=document.getElementById(CRM.ui.focus||'');if(f&&f.focus){f.focus();CRM.ui.focus=''}}
function crmOpen(id){cid=+id;CRM.ui.lastCid=cid;CRM.ui.back=SUB['Clients'];SUB['Clients']='Client Book';if(typeof tab!=='undefined'&&tab!=='Clients'){openTab('Clients','Client Book');return}go();const m=document.getElementById('main');if(m&&crmNarrow())m.scrollTop=0}
function crmBack(){cid=null;CRM.ui.lastCid=null;const b=CRM.ui.back;CRM.ui.back='';SUB['Clients']=b&&b!=='Client Book'?b:'Client Book';go()}
function crmNarrow(){const m=document.getElementById('main');return(m&&m.clientWidth?m.clientWidth-40:IW())<1000}
/* ---------- undo + toasts + celebration ---------- */
function crmTx(fn){CRM.rec=[];let out;try{out=fn()}finally{}const rec=CRM.rec;CRM.rec=null;return{out,undo:()=>crmUndoRec(rec)}}
function crmUndoRec(rec){rec.slice().reverse().forEach(r=>{const cur=(CRM.docs[r.p]||{})[r.k],pre=r.k[0];let patch;
 if(r.old===undefined)patch=pre==='c'?{del:1,dAt:Date.now()}:pre==='t'?{s:'x'}:{del:1};else{patch={};const o=r.old;Object.keys(cur||{}).forEach(f=>{if(JSON.stringify(cur[f])!==JSON.stringify(o[f]))patch[f]=o[f]===undefined?null:crmClone(o[f])});if(!Object.keys(patch).length)return}
 const meta=r.p.indexOf('crme/')===0?crmMeta(r.p):{};crmW(r.p,Object.assign(meta,{[r.k]:patch}))});CRM.cache={};go()}
function crmToast(m,undo,act){let e=document.getElementById('crmut');if(!e){e=document.createElement('div');e.id='crmut';e.setAttribute('role','status');e.setAttribute('aria-live','polite');document.body.appendChild(e)}
 CRM.ui.undo=undo||null;CRM.ui.uact=act||null;e.innerHTML=`<span>${esc(m)}</span>${act?`<button class="btn sm" onclick="crmUAct()">${esc(act[0])}</button>`:''}${undo?'<button class="btn sm o" onclick="crmUndo()">Undo</button>':''}<button class=x aria-label="Dismiss" onclick="crmUHide()">&times;</button>`;e.className='on';clearTimeout(CRM.ui.ut);CRM.ui.ut=setTimeout(crmUHide,undo?8000:4200)}
function crmUHide(){const e=document.getElementById('crmut');if(e)e.className=''}
function crmUndo(){const u=CRM.ui.undo;CRM.ui.undo=null;crmUHide();if(u){u();toast('Undone',1)}}
function crmUAct(){const a=CRM.ui.uact;crmUHide();if(a)a[1]()}
function crmConfetti(){if(typeof RM!=='undefined'&&RM)return;const h=document.createElement('div');h.className='crm-cf';h.setAttribute('aria-hidden','true');const cols=['#ff1f4f','#ffcf40','#3ddc97','#f4f4f6','#ff6b8a'];let s='';for(let i=0;i<28;i++)s+=`<i style="--x:${(Math.random()*2-1)*46}vw;--y:${-20-Math.random()*50}vh;--r:${Math.random()*720-360}deg;--d:${(.9+Math.random()*.7).toFixed(2)}s;background:${cols[i%5]}"></i>`;h.innerHTML=s;document.body.appendChild(h);setTimeout(()=>h.remove(),1900)}
/* ---------- quick capture ---------- */
function crmCapHtml(){return`<div class=crm-cap ondragover="event.preventDefault();this.classList.add('drop')" ondragleave="this.classList.remove('drop')" ondrop="crmDropFile(event)">
<label for=crmqc class=crm-sr>Quick capture</label><input id=crmqc autocomplete=off placeholder="Type or paste a lead: Mary Jones 412-555-0102 62 PA final expense facebook" oninput="crmCapPrev()" onkeydown="if(event.key==='Enter'){event.preventDefault();crmCapGo()}" onpaste="crmCapPaste(event)" aria-describedby=crmcp>
<button class=btn onclick="crmCapGo()">Add lead</button></div><div id=crmcp class=crm-cp aria-live=polite>Press Enter to add. Paste several lines or drop a CSV file to import a list.</div>`}
function crmCapPrev(){const i=document.getElementById('crmqc'),o=document.getElementById('crmcp');if(!i||!o)return;const v=i.value.trim();if(!v){o.innerHTML='Press Enter to add. Paste several lines or drop a CSV file to import a list.';return}const p=crmParse(v);
 const f=[['Name',p.name],['Phone',p.phone],['Age',p.age],['DOB',p.dob],['State',p.state],['Product',p.prod],['Source',p.src],['Email',p.email]].filter(x=>x[1]);o.innerHTML=f.length?f.map(x=>`<span>${x[0]} <b>${esc(x[1])}</b></span>`).join(''):'Keep typing: a name or phone number is enough.'}
function crmCapPaste(e){const t=(e.clipboardData||globalThis.clipboardData||{getData:()=>''}).getData('text');if(t&&/[\r\n]/.test(t.trim())){e.preventDefault();crmImport(t)}}
function crmCapGo(force){const i=document.getElementById('crmqc');if(!i)return;const v=i.value.trim();if(!v)return toast('Type a name and phone number first.');const p=crmParse(v);if(!p.name&&!p.phone&&!p.email)return toast('Add at least a name or a phone number.');
 if(!force){const d=crmFindDup(p,crmDupIndex(crmAll()));if(d){CRM.ui.dupOf=d.c.id;document.getElementById('crmcp').innerHTML=`<span class=neg>Possible duplicate of <b>${esc(d.c.name)}</b> (${esc(d.why)}).</span> <button class="btn sm o" onclick="crmOpen(${d.c.id})">Open</button> <button class="btn sm" onclick="crmCapGo(1)">Add anyway</button>`;return}}
 const tx=crmTx(()=>crmCreate({name:p.name||'New lead',phone:p.phone||'',phone2:p.phone2||'',email:p.email||'',age:p.age||'',dob:p.dob||'',state:p.state||'',zip:p.zip||'',prod:p.prod||'',src:p.src||'',notes:p.notes||'',info:p.tobacco?{tobacco:p.tobacco}:{}}));
 i.value='';CRM.ui.focus='crmqc';CRM.ui.tf='all';go();crmToast((tx.out.name||'Lead')+' added. First call is due now.',tx.undo)}
function crmDropFile(e){e.preventDefault();const f=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0];if(f)crmReadFile(f);else{const t=e.dataTransfer&&e.dataTransfer.getData('text');if(t)crmImport(t)}}
function crmReadFile(f){if(f.size>5e6)return toast('That file is over 5 MB. Split it into smaller lists.');const r=new FileReader();r.onload=()=>crmImport(String(r.result||''),f.name);r.onerror=()=>toast('That file could not be read.');r.readAsText(f)}
/* ---------- import (paste / CSV) ---------- */
function crmImport(text,name){const md=document.getElementById('md');CRM.ui.imp={text:text||'',name:name||'',map:null,own:WHO,skip:{}};
 md.innerHTML=`<div class=mb onclick="if(event.target==this)closeM()"><div class="c crm-wide" role=dialog aria-label="Import leads"><h4>Import leads</h4><p class=mut>Paste rows from a spreadsheet or a lead email, or choose a CSV file. Nothing leaves this device until you press Import.</p>
<div id=crmimb>${text?'':`<label for=crmit>Paste here</label><textarea id=crmit rows=7 placeholder="Name, Phone, Age, State, Product, Source&#10;Mary Jones, 412-555-0102, 62, PA, Final Expense, Facebook"></textarea>
<div class=crm-row2><label class="btn o crm-file">Choose CSV file<input type=file accept=".csv,.tsv,.txt,text/csv,text/plain" onchange="if(this.files[0])crmReadFile(this.files[0])"></label><button class=btn onclick="const t=document.getElementById('crmit').value;if(!t.trim())return toast('Paste some rows first.');crmImport(t)">Preview</button><button class="btn o" onclick="closeM()">Cancel</button></div>`}</div></div></div>`;
 if(text)crmImpPrev();else{const t=document.getElementById('crmit');if(t)t.focus()}}
function crmImpRows(){const I=CRM.ui.imp;const rows=crmCsv(I.text);if(!I.map){const mp=crmMapCols(rows);if(rows.length===1&&!mp.head&&!(rows[0].length>1)){I.single=1}I.map=mp}return rows}
function crmImpLeads(){const I=CRM.ui.imp,rows=crmImpRows();let leads;if(rows.length&&rows.every(r=>r.length===1)&&!I.map.head){leads=rows.map(r=>crmParse(r[0])).map(p=>Object.assign({name:'',phone:'',email:'',info:{}},p,{info:p.tobacco?{tobacco:p.tobacco}:{}})).filter(o=>o.name||o.phone||o.email)}else leads=crmRowsToLeads(rows,I.map);return crmDedupe(leads,crmAll())}
function crmImpPrev(){const I=CRM.ui.imp,b=document.getElementById('crmimb');if(!b)return;const rows=crmImpRows(),res=crmImpLeads(),cols=(rows[0]||[]).length,head=I.map.head?rows[0]:null,keys=['','name','first','last','phone','phone2','email','age','dob','state','city','zip','street','prod','src','ven','cost','notes','owner','budget','tobacco'];
 const lab={'':'Skip',name:'Full name',first:'First name',last:'Last name',phone:'Phone',phone2:'Alt phone',email:'Email',age:'Age',dob:'Date of birth',state:'State',city:'City',zip:'ZIP',street:'Street',prod:'Product',src:'Source',ven:'Vendor',cost:'Lead cost',notes:'Notes',owner:'Owner',budget:'Budget',tobacco:'Tobacco'};
 const inv={};Object.keys(I.map.map).forEach(k=>inv[I.map.map[k]]=k);const multi=cols>1||I.map.head;
 const ok=res.filter(r=>!r.dup&&!r.inBatch&&!I.skip[r.i]).length,dups=res.filter(r=>r.dup||r.inBatch).length;
 const ags=crmAgents();
 b.innerHTML=`${multi?`<div class=crm-map><small>Columns (auto-detected, change if needed)</small><div class=crm-mapr>${Array.from({length:cols},(_,i)=>`<label>${esc(head?head[i]:'Column '+(i+1))}<select onchange="crmImpMap(${i},this.value)">${keys.map(k=>`<option value="${k}" ${inv[i]===k||(!inv[i]&&!k)?'selected':''}>${lab[k]}</option>`).join('')}</select></label>`).join('')}</div></div>`:''}
<div class=crm-imps><span><b>${res.length}</b> rows</span><span class=pos><b>${ok}</b> new</span><span class=${dups?'neg':'mut'}><b>${dups}</b> possible duplicates (left out unless you tick them)</span></div>
<div class="sc crm-impg"><table><tr><th><span class=crm-sr>Import</span><th>Name<th>Phone<th>Age<th>State<th>Product<th>Source<th>Check</tr>${res.slice(0,300).map(r=>{const o=r.o,on=(!r.dup&&!r.inBatch)?!I.skip[r.i]:!!I.skip[r.i];return`<tr class="${r.dup||r.inBatch?'crm-dupr':''}"><td><input type=checkbox aria-label="Import ${esc(o.name||o.phone)}" ${on?'checked':''} onchange="crmImpTick(${r.i})"><td>${esc(o.name||'-')}<td>${esc(o.phone||'-')}<td>${esc(o.age||'')}<td>${esc(o.state||'')}<td>${esc(o.prod||'')}<td>${esc(o.src||'')}<td>${r.dup?`<span class=neg>Duplicate of ${esc(r.dup.name)} (${esc(r.why)})</span>`:r.inBatch?`<span class=neg>${esc(r.why)}</span>`:'<span class=pos>New</span>'}</tr>`}).join('')}</table>${res.length>300?`<small>Showing the first 300 of ${res.length} rows. All ticked rows are imported.</small>`:''}</div>
<div class=crm-row2>${crmOwnerView()?`<label class=crm-inl>Assign to <select id=crmimo onchange="CRM.ui.imp.own=this.value"><option value="${esc(WHO)}">Me</option><option value="">Unassigned (agents can claim)</option>${ags.filter(a=>a!==WHO).map(a=>`<option ${I.own===a?'selected':''}>${esc(a)}</option>`).join('')}</select></label>`:''}
<button class=btn id=crmimgo onclick="crmImpGo()">Import ${crmImpCount(res)} leads and start follow-up</button><button class="btn o" onclick="closeM()">Cancel</button></div>`}
function crmImpCount(res){const I=CRM.ui.imp;return res.filter(r=>(!r.dup&&!r.inBatch)?!I.skip[r.i]:!!I.skip[r.i]).length}
function crmImpMap(i,k){const m=CRM.ui.imp.map.map;Object.keys(m).forEach(x=>{if(m[x]===i)delete m[x]});if(k)m[k]=i;crmImpPrev()}
function crmImpTick(i){const s=CRM.ui.imp.skip;s[i]=!s[i];crmImpPrev()}
function crmImpGo(){const I=CRM.ui.imp,res=crmImpLeads(),pick=res.filter(r=>(!r.dup&&!r.inBatch)?!I.skip[r.i]:!!I.skip[r.i]);if(!pick.length)return toast('Tick at least one row to import.');
 const own=crmOwnerView()?I.own:WHO,ags=crmAgents();const tx=crmTx(()=>pick.map(r=>{const o=Object.assign({},r.o);let ow=own;if(o.owner&&ags.indexOf(o.owner)>=0&&crmOwnerView())ow=o.owner;delete o.owner;o.owner=ow;return crmCreate(o,{note:'Imported'+(I.name?' from '+I.name:'')+(o.src?' ('+o.src+')':''),ev:'import'})}));
 closeM();SUB['Clients']='Today';CRM.ui.tf='fresh';cid=null;go();crmToast('Imported '+pick.length+' lead'+(pick.length>1?'s':'')+'. First calls are on Today.',tx.undo)}
/* ---------- new lead (full form) ---------- */
function crmNewLead(pre){pre=pre||{};const md=document.getElementById('md'),ags=crmAgents();
 const sel=(id,l,opts,v)=>`<label for=${id}>${l}</label><select id=${id}>${opts.map(o=>`<option value="${esc(o[0])}" ${o[0]===v?'selected':''}>${esc(o[1])}</option>`).join('')}</select>`;
 md.innerHTML=`<div class=mb onclick="if(event.target==this)closeM()"><div class="c crm-mid" role=dialog aria-label="New lead"><h4>New lead</h4><div class=crm-f2>
<div><label for=crmn_name>Full name</label><input id=crmn_name value="${esc(pre.name||'')}" autocomplete=off></div><div><label for=crmn_phone>Phone</label><input id=crmn_phone type=tel value="${esc(pre.phone||'')}"></div>
<div><label for=crmn_email>Email</label><input id=crmn_email type=email value="${esc(pre.email||'')}"></div><div><label for=crmn_age>Age</label><input id=crmn_age type=number min=18 max=110 value="${esc(pre.age||'')}"></div>
<div><label for=crmn_dob>Date of birth</label><input id=crmn_dob type=date value="${esc(pre.dob||'')}"></div><div><label for=crmn_state>State</label><input id=crmn_state list=crmstl value="${esc(pre.state||'')}" placeholder="PA"><datalist id=crmstl>${Object.keys(CRM_STN).map(k=>`<option value="${k}">${CRM_STN[k]}</option>`).join('')}</datalist></div>
<div>${sel('crmn_prod','Product interest',[['','Not sure yet'],...CRM_PROD.map(p=>[p,p])],pre.prod||'')}</div><div><label for=crmn_src>Lead source</label><input id=crmn_src list=crmsrl value="${esc(pre.src||'')}"><datalist id=crmsrl>${CRM_SRC.map(s=>`<option>${s}</option>`).join('')}</datalist></div>
${crmOwnerView()?`<div>${sel('crmn_own','Owner',[[WHO,'Me ('+WHO+')'],['','Unassigned'],...ags.filter(a=>a!==WHO).map(a=>[a,a])],WHO)}</div>`:''}<div class=crm-full><label for=crmn_notes>Notes</label><textarea id=crmn_notes rows=2 placeholder="Anything they told you: who it is for, budget, health"></textarea></div></div>
<div id=crmn_dup class=crm-cp></div><button class=btn onclick="crmNewSave(0)">Add lead</button> <button class="btn o" onclick="closeM()">Cancel</button></div></div>`;const f=document.getElementById('crmn_name');if(f)f.focus()}
function crmNewSave(force){const v=k=>{const e=document.getElementById('crmn_'+k);return e?e.value.trim():''};const o={name:v('name'),phone:crmFmtPhone(v('phone'))||v('phone'),email:v('email').toLowerCase(),age:v('age'),dob:v('dob'),state:crmStateCode(v('state'))||v('state'),prod:v('prod'),src:v('src'),notes:v('notes')};
 if(!o.name&&!o.phone)return toast('Enter a name or a phone number.');if(o.dob&&!o.age)o.age=String(crmAgeOf({dob:o.dob})||'');if(crmOwnerView()){const e=document.getElementById('crmn_own');if(e)o.owner=e.value}
 if(!force){const d=crmFindDup(o,crmDupIndex(crmAll()));if(d){document.getElementById('crmn_dup').innerHTML=`<span class=neg>Possible duplicate of <b>${esc(d.c.name)}</b> (${esc(d.why)}).</span> <button class="btn sm o" onclick="closeM();crmOpen(${d.c.id})">Open ${esc(crmFirst(d.c.name))}</button> <button class="btn sm" onclick="crmNewSave(1)">Add anyway</button>`;return}}
 const tx=crmTx(()=>crmCreate(o));closeM();go();crmToast(o.name+' added. First call is due now.',tx.undo,['Open',()=>crmOpen(tx.out.id)])}
/* ---------- Today ---------- */
function crmVToday(){const w=crmScope(),k=crmCounts(w),Q=crmQueue(w),f=CRM.ui.tf||'all',now=Date.now();
 const flt=it=>{if(f==='all')return true;if(!it.t)return f==='fresh'&&it.c.stage==='new'&&!it.c.ft;const st=crmDueState(it.t,now),nw=it.c.stage==='new'&&!it.c.ft;return f==='over'?st==='over'&&(!nw||it.t.ty==='appt'):f==='today'?(st!=='over'&&it.t.ty!=='appt'&&!nw):f==='appt'?it.t.ty==='appt':f==='fresh'?(it.c.stage==='new'&&!it.c.ft):true};
 const L=Q.filter(flt),lim=CRM.ui.tmore||40,sel=crmGet(CRM.ui.tsel)||(L[0]&&L[0].c)||null;
 const tile=(key,lab,n,cls,go2)=>`<button class="crm-kt ${cls||''} ${f===key?'on':''}" onclick="${go2||`CRM.ui.tf=CRM.ui.tf==='${key}'?'all':'${key}';CRM.ui.tmore=0;go()`}" aria-pressed="${f===key}"><small>${lab}</small><b>${crmNum(n)}</b></button>`;
 const agSel=crmOwnerView()?`<label class=crm-inl>View <select onchange="CRM.ui.ag=this.value;go()" aria-label="Show the queue for"><option value="">Everyone</option>${crmAgents().map(a=>`<option ${CRM.ui.ag===a?'selected':''}>${esc(a)}</option>`).join('')}</select></label>`:'';
 const empty=!crmVisible(w).length?`<div class="c crm-empty"><h4>Paste your first leads here</h4><p>Type one lead in the box above and press Enter, for example <b>Mary Jones 412-555-0102 62 PA final expense facebook</b>. To bring a whole list, paste spreadsheet rows or drop a CSV file on the box.</p><button class=btn onclick="crmImport()">Import a list</button></div>`
  :!L.length?`<div class="c crm-empty"><h4>${f==='all'?'All caught up':'Nothing here'}</h4><p>${f==='all'?'No follow-ups are due and every new lead has been called. Nice work. Check the Pipeline for deals to push forward.':'Nothing matches this filter right now.'}</p>${f!=='all'?`<button class="btn o" onclick="CRM.ui.tf='all';go()">Show everything due</button>`:`<button class="btn o" onclick="crmSub('Pipeline')">Open Pipeline</button>`}</div>`:'';
 return crmCapHtml()+`<div class=crm-k>${tile('over','Overdue',k.over,'over')}${tile('today','Due today',k.today,'today')}${tile('appt','Appointments today',k.appt,'')}${tile('fresh','New, not called',k.fresh,'fresh')}${tile('deliv','Deliveries due',k.deliv,'',"CRM.ui.view='deliv';cid=null;crmSub('Client Book')")}${tile('bday','Birthdays this week',k.bday,'',"CRM.ui.view='bday';cid=null;crmSub('Client Book')")}</div>
<div class=crm-tg><div class=crm-ql><div class=crm-qh><h3>${f==='all'?'Up next':{over:'Overdue',today:'Due today',appt:'Appointments today',fresh:'New leads, not called'}[f]} <small class=mut>${L.length} ${L.length===1?'person':'people'}, best first</small></h3>${agSel}</div>
${empty||L.slice(0,lim).map((it,i)=>crmQRow(it,i,sel)).join('')+(L.length>lim?`<button class="btn o crm-more" onclick="CRM.ui.tmore=${lim+40};go()">Show ${Math.min(40,L.length-lim)} more</button>`:'')}</div>
<div class=crm-pane role=complementary aria-label="Selected contact">${sel?crmPane(sel):''}</div></div>`}
function crmQRow(it,i,sel){const c=it.c,t=it.t,st=t?crmDueState(t):'',why=it.why,red=/Overdue|Outside/.test(why),win=crmWindow(c);
 const nx=t?`${esc(crmTL(t))} &middot; <span class="${st==='over'||st==='late'?'neg':'crm-gold'}">${crmWhen(t.due,t.ad)}</span>`:'Not called yet';
 const meta=[c.age?c.age+'y':'',c.state?esc(c.state)+(win.known?' '+win.label:''):'',esc(c.prod||''),esc(c.src||'')].filter(Boolean).join(' &middot; ');
 return`<div class="crm-qr ${st==='over'?'over':st?'today':'fresh'} ${sel&&sel.id===c.id?'on':''}" id=crmq${c.id} data-id=${c.id}><div class=crm-qrow>
<button class=crm-qm onclick="crmTSel(${c.id})" aria-label="${esc(c.name)}: ${esc(why)}">${crmAv(c,40)}<span class=crm-qn><b>${esc(c.name)}</b><small><span class="crm-why ${red?'crm-bad':''}">${esc(why)}</span>${crmStPill(c.stage)}${meta?`<span>${meta}</span>`:''}</small><small class=crm-qx>${nx} &middot; last touch ${crmAgo(c.lt)}</small></span></button>
<div class=crm-qa>${crmLink(crmTel(c),'Call','crm-ib call',`crmCallTap(${c.id})`,'Call '+c.name)}${crmLink(crmSms(c,t),'Text','crm-ib',`crmTextTap(${c.id})`,'Text '+c.name)}${t?`<button class=crm-ib onclick="crmTDone('${crmQS(t.id)}')" aria-label="Mark done">Done</button><button class=crm-ib onclick="crmSnoozeMenu('${crmQS(t.id)}')" aria-label="Snooze">Snooze</button>`:`<button class=crm-ib onclick="crmCallTap(${c.id})">Log</button>`}</div></div>
${CRM.ui.calling===c.id?crmOutBar(c):''}</div>`}
function crmTSel(id){if(crmNarrow())return crmOpen(id);CRM.ui.tsel=+id;go()}
function crmCallTap(id){CRM.ui.calling=+id;CRM.ui.tsel=+id;CRM.ui.callAt=Date.now();setTimeout(()=>go(),60)}
function crmTextTap(id){const c=crmGet(id);if(!c)return;setTimeout(()=>{crmEv(id,'text',{t:crmTxtFor(c,crmNext(id)),o:'sent'});crmToast('Text logged for '+crmFirst(c.name)+'. Your messages app has the words ready.',null)},80)}
function crmOutBar(c){const B=(o,l,cls)=>`<button class="crm-ob-b ${cls||''}" onclick="crmOut(${c.id},'${o}')">${l}</button>`;
 return`<div class=crm-ob role=group aria-label="How did the call with ${esc(c.name)} go?"><small>How did it go?</small><div class=crm-obg>${B('na',CRM_OUTS.na)}${B('vm',CRM_OUTS.vm)}${B('int',CRM_OUTS.int,'crm-ok')}${B('appt',CRM_OUTS.appt,'crm-hi')}${B('cb',CRM_OUTS.cb)}${B('ni',CRM_OUTS.ni)}${B('bad',CRM_OUTS.bad)}${B('dnc',CRM_OUTS.dnc,'crm-bad')}</div><button class="btn o sm" onclick="CRM.ui.calling=null;go()">Cancel</button></div>`}
function crmOut(id,o){const c=crmGet(id);if(!c)return;if(o==='appt')return crmSchedule(id,'appt');if(o==='cb')return crmSchedule(id,'cb');
 const run=()=>{const tx=crmTx(()=>crmOutcome(id,o));CRM.ui.calling=null;go();const n=crmNext(id);crmToast('Logged: '+CRM_OUT[o]+(n?'. Next: '+(CRM_TY[n.ty]||'Task')+' '+crmWhen(n.due,n.ad):'')+'.',tx.undo,(o==='vm'||o==='na')&&crmSms(c)?['Send text',()=>{location.href=crmSms(crmGet(id)||c)}]:null)};
 if(o==='dnc')return ask('Mark '+esc(c.name)+' as Do Not Contact? Every open follow-up is cancelled.',run);run()}
function crmTDone(tid){const el=document.querySelector('[data-t="'+tid+'"]')||(()=>{const t=CRM.t.get(tid);return t?document.getElementById('crmq'+t.c):null})();const fin=()=>{const tx=crmTx(()=>crmDone(tid));go();const n=tx.out;crmToast('Done.'+(n?' Next: '+(CRM_TY[n.ty]||'Task')+' '+crmWhen(n.due,n.ad)+'.':''),tx.undo)};
 if(el&&!(typeof RM!=='undefined'&&RM)){el.classList.add('crm-gone');setTimeout(fin,320)}else fin()}
function crmQuick(){const d=new Date(),t=d.getTime(),at=(days,h,m)=>{const x=new Date();x.setDate(x.getDate()+days);x.setHours(h,m||0,0,0);return x.getTime()},mon=()=>{const x=new Date();x.setDate(x.getDate()+((8-x.getDay())%7||7));x.setHours(10,0,0,0);return x.getTime()};
 return[['In 1 hour',t+36e5],['In 3 hours',t+3*36e5],['Tomorrow 10 AM',at(1,10)],['Tomorrow 6 PM',at(1,18)],['Monday 10 AM',mon()],['Next week',at(7,10)]]}
function crmSnoozeMenu(tid){const t=CRM.t.get(tid);if(!t)return;const c=crmGet(t.c),md=document.getElementById('md');
 md.innerHTML=`<div class=mb onclick="if(event.target==this)closeM()"><div class=c role=dialog aria-label="Snooze"><h4>Snooze ${esc(c?c.name:'')}</h4><p class=mut>${esc(CRM_TY[t.ty]||'Task')} moves to the time you pick.</p><div class=crm-qp>${crmQuick().map(q=>`<button class="btn o" onclick="crmSnoozeGo('${crmQS(tid)}',${q[1]})">${q[0]}</button>`).join('')}</div>
<label for=crmsz>Or pick a date and time</label><input id=crmsz type=datetime-local><button class=btn onclick="const v=document.getElementById('crmsz').value;if(!v)return toast('Pick a date and time.');crmSnoozeGo('${crmQS(tid)}',new Date(v).getTime())">Snooze</button> <button class="btn o" onclick="closeM()">Cancel</button></div></div>`}
function crmSnoozeGo(tid,ts){closeM();const tx=crmTx(()=>crmSnooze(tid,ts));go();crmToast('Snoozed to '+crmWhen(ts)+'.',tx.undo)}
function crmSchedule(id,kind){const c=crmGet(id);if(!c)return;const md=document.getElementById('md'),isA=kind==='appt',isCb=kind==='cb';CRM.ui.sch={id,kind};
 md.innerHTML=`<div class=mb onclick="if(event.target==this)closeM()"><div class=c role=dialog aria-label="Schedule"><h4>${isA?'Appointment with ':isCb?'Call back ':'Schedule for '}${esc(c.name)}</h4>
${isA||isCb?'':`<label for=crmsct>Type</label><select id=crmsct>${['call','appt','fu','text','deliv','review'].map(k=>`<option value=${k}>${CRM_TY[k]}</option>`).join('')}</select>`}<div class=crm-qp>${crmQuick().map(q=>`<button class="btn o" onclick="crmSchGo(${q[1]})">${q[0]}</button>`).join('')}</div>
<label for=crmscw>Or pick a date and time</label><input id=crmscw type=datetime-local><label for=crmscn>Note (optional)</label><input id=crmscn placeholder="${isA?'Zoom, phone or in person':'What to cover'}">
<button class=btn onclick="const v=document.getElementById('crmscw').value;if(!v)return toast('Pick a date and time.');crmSchGo(new Date(v).getTime())">${isA?'Book appointment':'Schedule'}</button> <button class="btn o" onclick="closeM()">Cancel</button></div></div>`}
function crmSchGo(ts){const S=CRM.ui.sch;if(!S)return;const n=(document.getElementById('crmscn')||{}).value||'',ty=S.kind==='appt'?'appt':S.kind==='cb'?'call':((document.getElementById('crmsct')||{}).value||'fu');closeM();
 const c=crmGet(S.id),tx=crmTx(()=>{if(S.kind==='appt'||S.kind==='cb')crmOutcome(S.id,S.kind,{when:ts});else crmTask({c:S.id,ty,t:n||CRM_TY[ty],due:ts,ow:c?c.owner:WHO});if(n&&(S.kind==='appt'||S.kind==='cb')){const t=crmOpenTasks(S.id).find(x=>x.due===ts);if(t)crmTaskPatch(t.id,{t:(S.kind==='appt'?'Appointment':'Call back')+': '+n})}});
 CRM.ui.calling=null;go();if(S.kind==='appt')crmConfetti();crmToast((S.kind==='appt'?'Appointment booked ':S.kind==='cb'?'Call back set ':'Scheduled ')+crmWhen(ts)+'.',tx.undo,S.kind==='appt'&&c&&crmSms(c)?['Text confirmation',()=>{const cc=crmGet(S.id);const t=crmOpenTasks(S.id).find(x=>x.ty==='appt');location.href=crmSms(cc,t)}]:null)}
function crmCallNext(){const q=crmQueue(crmScope());if(!q.length)return toast('Nobody is waiting for a call right now.',1);const c=q[0].c;cid=null;CRM.ui.tf='all';CRM.ui.tsel=c.id;CRM.ui.calling=c.id;openTab('Clients','Today');
 try{if(matchMedia('(pointer:coarse)').matches&&crmTel(c))location.href=crmTel(c)}catch(e){}toast('Next up: '+c.name+(c.phone?' '+c.phone:''),1)}
/* ---------- detail pane (desktop Today) ---------- */
function crmPane(c){const t=crmNext(c.id),ev=crmEvents(c.id).slice(-6).reverse(),win=crmWindow(c);
 return`<div class="c crm-pc"><div class=crm-ph>${crmAv(c,52)}<div><b class=crm-pn>${esc(c.name)}</b><small>${[c.age?c.age+' years':'',c.state?(CRM_STN[c.state]||c.state):'',c.phone].filter(Boolean).map(esc).join(' &middot; ')}</small><div class=crm-chips>${crmStPill(c.stage)}${win.known?`<span class="crm-why ${win.ok?'crm-ok':'crm-bad'}">${win.ok?'OK to call':'Outside hours'} ${win.label}</span>`:''}</div></div></div>
<div class=crm-pa>${crmLink(crmTel(c),'Call','crm-ib call',`crmCallTap(${c.id})`)}${crmLink(crmSms(c,t),'Text','crm-ib',`crmTextTap(${c.id})`)}<button class=crm-ib onclick="crmSchedule(${c.id})">Schedule</button><button class=crm-ib onclick="crmOpen(${c.id})">Open</button></div>
${t?`<h4>Next action</h4><div class=crm-nx data-t="${crmQS(t.id)}"><b>${esc(crmTL(t))}</b><small class="${crmDueState(t)==='over'?'neg':'crm-gold'}">${crmWhen(t.due,t.ad)}</small><div><button class="btn sm" onclick="crmTDone('${crmQS(t.id)}')">Done</button> <button class="btn sm o" onclick="crmSnoozeMenu('${crmQS(t.id)}')">Snooze</button></div></div>`:''}
${c.info&&(c.info.health||c.info.goal||c.info.budget)?`<h4>Good to know</h4><p class=crm-gk>${[c.info.goal?'Goal: '+esc(c.info.goal):'',c.info.budget?'Budget: '+esc(c.info.budget):'',c.info.health?'Health: '+esc(c.info.health):''].filter(Boolean).join('<br>')}</p>`:''}
<h4>What happened so far</h4>${ev.length?ev.map(crmEvHtml).join(''):'<p class=mut>Nothing logged yet. Every call, text and note shows up here.</p>'}</div>`}
/* ---------- Pipeline ---------- */
function crmPF(L){const f=CRM.ui.pf||{},q=String(CRM.ui.pq||'').toLowerCase();return L.filter(c=>(!f.ag||c.owner===f.ag||(f.ag==='-'&&(!c.owner||c.owner==='Unassigned')))&&(!f.src||c.src===f.src)&&(!f.prod||c.prod===f.prod)&&(!f.tag||(c.tags||[]).indexOf(f.tag)>=0)&&(!q||(c.name+' '+c.phone+' '+c.email).toLowerCase().indexOf(q)>=0))}
function crmVPipe(){const all=crmVisible(),L=crmPF(all),f=CRM.ui.pf||{},now=Date.now(),by={},narrow=crmNarrow();CRM_ST.forEach(s=>by[s]=[]);L.forEach(c=>(by[c.stage]||by.new).push(c));
 const tby=crmTasksBy(),srcs=[...new Set(all.map(c=>c.src).filter(Boolean))].sort(),prods=[...new Set(all.map(c=>c.prod).filter(Boolean))].sort(),tags=[...new Set(all.flatMap(c=>c.tags||[]))].sort();
 const opt=(k,lab,list)=>`<label class=crm-inl>${lab}<select onchange="CRM.ui.pf=Object.assign({},CRM.ui.pf,{${k}:this.value});go()"><option value="">All</option>${list.map(x=>`<option value="${esc(x[0])}" ${f[k]===x[0]?'selected':''}>${esc(x[1])}</option>`).join('')}</select></label>`;
 const cur=CRM.ui.pcol||'new';
 const bar=`<div class=crm-pfb>${crmOwnerView()?opt('ag','Agent',[...crmAgents().map(a=>[a,a]),['-','Unassigned']]):''}${opt('src','Source',srcs.map(x=>[x,x]))}${opt('prod','Product',prods.map(x=>[x,x]))}${tags.length?opt('tag','Tag',tags.map(x=>[x,x])):''}<label class=crm-inl>Find<input value="${esc(CRM.ui.pq||'')}" placeholder="Name or phone" oninput="CRM.ui.pq=this.value;clearTimeout(CRM.ui.pqt);CRM.ui.pqt=setTimeout(()=>{CRM.ui.focus='crmpq';go()},250)" id=crmpq></label></div>`;
 const tot=L.filter(c=>c.stage!=='dead').reduce((a,c)=>a+(+c.ap||CRM_PAP[c.prod]||0),0),wt=L.reduce((a,c)=>a+(+c.ap||CRM_PAP[c.prod]||0)*(CRM_SP[c.stage]||0),0);
 const col=s=>{const cs=by[s].map(c=>({c,t:(tby.get(c.id)||[])[0],d:Math.floor((now-(c.sAt||c.at||now))/864e5)})).sort((a,b)=>(a.t?a.t.due:9e15)-(b.t?b.t.due:9e15)||b.d-a.d),pot=by[s].reduce((a,c)=>a+(+c.ap||CRM_PAP[c.prod]||0),0),stuck=cs.filter(x=>CRM_STUCK[s]&&x.d>CRM_STUCK[s]).length,lim=CRM.ui.more[s]||50,coll=CRM.ui.col[s]!==undefined?CRM.ui.col[s]:(s==='dead'&&!narrow);
  if(narrow&&s!==cur)return'';
  return`<section class="crm-col ${coll?'coll':''}" data-st="${s}" ondragover="event.preventDefault();this.classList.add('dz')" ondragleave="this.classList.remove('dz')" ondrop="crmDrop(event,'${s}')" aria-label="${esc(CRM_SN[s])}: ${by[s].length}">
<button class=crm-colh onclick="CRM.ui.col['${s}']=!${coll?1:0};go()" aria-expanded="${!coll}"><b>${esc(CRM_SN[s])}</b><span><em>${by[s].length}</em>${pot?' &middot; $'+Math.round(pot).toLocaleString():''}${stuck?` <i class=crm-wip>${stuck} stuck</i>`:''}</span></button>
${coll?'':`<div class=crm-cards>${cs.slice(0,lim).map(x=>crmCard(x,s)).join('')||'<p class="mut crm-ce">Drop a card here</p>'}${cs.length>lim?`<button class="btn o sm" onclick="CRM.ui.more['${s}']=${lim+50};go()">Show more (${cs.length-lim})</button>`:''}</div>`}</section>`};
 return bar+`<div class=crm-psum><span><b>${L.length}</b> in view</span><span>Open premium <b>$${Math.round(tot).toLocaleString()}</b></span><span>Weighted <b>$${Math.round(wt).toLocaleString()}</b></span></div>`+(narrow?`<div class=crm-pst role=tablist aria-label=Stages>${CRM_ST.map(s=>`<button role=tab aria-selected="${s===cur}" class="${s===cur?'on':''}" onclick="CRM.ui.pcol='${s}';go()">${esc(CRM_SN[s].split(' ')[0])} <em>${by[s].length}</em></button>`).join('')}</div>`:'')+`<div class="crm-board ${narrow?'one':''}">${CRM_ST.map(col).join('')}</div>`}
function crmCard(x,s){const c=x.c,t=x.t,st=t?crmDueState(t):'',stuck=CRM_STUCK[s]&&x.d>CRM_STUCK[s],age=crmAgeOf(c);
 return`<div class="crm-card ${stuck?'stuck':''}" draggable=true ondragstart="crmDrag(event,${c.id})" tabindex=0 role=button onclick="crmOpen(${c.id})" onkeydown="if(event.key==='Enter')crmOpen(${c.id})" aria-label="${esc(c.name)}, ${esc(CRM_SN[s])}">
<div class=crm-ch><b>${esc(c.name)}</b>${crmOwnAv(c.owner)}</div><small>${[age?age+'y':'',esc(c.prod||''),esc(c.state||'')].filter(Boolean).join(' &middot; ')||'No details yet'}</small>
<div class=crm-cfo>${t?`<span class="crm-nb ${st}">${esc(CRM_TY[t.ty]||'Task')} ${crmWhen(t.due,t.ad)}</span>`:`<span class="crm-nb none">No next step</span>`}<span class=crm-ds>${x.d}d</span>${stuck?'<i class=crm-wip>STUCK</i>':''}</div>
${crmNarrow()?`<select class=crm-cst onclick="event.stopPropagation()" onchange="crmStageSel(${c.id},this.value)" aria-label="Move ${esc(c.name)} to stage">${CRM_ST.map(z=>`<option value=${z} ${z===s?'selected':''}>${esc(CRM_SN[z])}</option>`).join('')}</select>`:''}</div>`}
function crmDrag(e,id){try{e.dataTransfer.setData('text/plain','crm:'+id);e.dataTransfer.effectAllowed='move'}catch(x){}CRM.ui.drag=id}
function crmDrop(e,st){e.preventDefault();let id=CRM.ui.drag;try{const d=e.dataTransfer.getData('text/plain');if(/^crm:\d+$/.test(d))id=+d.slice(4)}catch(x){}CRM.ui.drag=null;if(id)crmStageSel(id,st)}
function crmStageSel(id,st){const c=crmGet(id);if(!c||c.stage===st)return go();const from=c.stage,tx=crmTx(()=>crmStage(id,st,'moved by '+WHO));go();if(st==='client'||st==='issued')crmConfetti();crmToast(c.name+' moved to '+CRM_SN[st]+'.',tx.undo)}
/* ---------- Client Book (windowed list) ---------- */
const CRM_VIEWS=[['all','All'],['mine','My leads'],['hot','Hot'],['over','Overdue'],['deliv','Needs delivery'],['inforce','In force'],['lapse','Lapse risk'],['unas','Unassigned'],['bday','Birthdays']];
function crmBookList(){const v=CRM.ui.view||'all',q=String(CRM.ui.q||'').toLowerCase().trim(),qd=q.replace(/\D/g,''),sod=crmSOD(),tby=crmTasksBy(),now=Date.now(),wk=[];for(let i=0;i<7;i++){const d=new Date(now+i*864e5);wk.push((d.getMonth()+1)*100+d.getDate())}
 let L=crmVisible().filter(c=>{const t=(tby.get(c.id)||[])[0];switch(v){case'mine':return c.owner===WHO;case'hot':return(c.tags||[]).indexOf('Hot')>=0||c.stage==='appt'||c.stage==='quoted'||(c.stage==='new'&&!c.ft);case'over':return t&&t.due<sod;case'deliv':return c.stage==='issued'||(tby.get(c.id)||[]).some(x=>x.ty==='deliv');case'inforce':return c.stage==='client';
  case'lapse':return(c.tags||[]).some(x=>/lapse/i.test(x))||crmPolicies(c).some(p=>p.st==='Chargeback');case'unas':return!c.owner||c.owner==='Unassigned';case'bday':return c.dob&&wk.indexOf(+c.dob.slice(5,7)*100+ +c.dob.slice(8,10))>=0;default:return true}});
 if(q)L=L.filter(c=>(c.name+' '+(c.email||'')+' '+(c.tags||[]).join(' ')+' '+(c.state||'')).toLowerCase().indexOf(q)>=0||(qd.length>=3&&String(c.phone||'').replace(/\D/g,'').indexOf(qd)>=0));
 const s=CRM.ui.sort||'next',nd=c=>{const t=(tby.get(c.id)||[])[0];return t?t.due:9e15};
 L=L.slice().sort(s==='name'?(a,b)=>String(a.name).localeCompare(String(b.name)):s==='touch'?(a,b)=>(b.lt||0)-(a.lt||0):s==='new'?(a,b)=>(b.at||0)-(a.at||0):s==='stage'?(a,b)=>crmRank(a.stage)-crmRank(b.stage)||nd(a)-nd(b):(a,b)=>nd(a)-nd(b)||(b.at||0)-(a.at||0));return L}
function crmVBook(){const c=cid!=null?crmGet(cid):null,narrow=crmNarrow();if(c&&narrow)return crm360(c,1);const L=CRM.ui.list=crmBookList(),n=Object.keys(CRM.ui.sel).length;
 return`<div class="crm-bk ${c?'has':''}"><div class="c crm-lw"><div class=crm-bt><label for=crmbq class=crm-sr>Search contacts</label><input id=crmbq type=search placeholder="Search name, phone, email, tag" value="${esc(CRM.ui.q||'')}" oninput="CRM.ui.q=this.value;crmBookUpd()">
<select aria-label="Sort by" onchange="CRM.ui.sort=this.value;crmBookUpd()">${[['next','Next action'],['name','Name A-Z'],['touch','Last touch'],['new','Newest'],['stage','Stage']].map(o=>`<option value=${o[0]} ${CRM.ui.sort===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></div>
<div class=crm-vw role=tablist aria-label="Saved views">${CRM_VIEWS.map(v=>`<button class="chip ${CRM.ui.view===v[0]||(!CRM.ui.view&&v[0]==='all')?'on':''}" onclick="CRM.ui.view='${v[0]}';CRM.ui.scroll=0;go()">${v[1]}</button>`).join('')}</div>
<div id=crmbb class="crm-bb ${n?'on':''}">${crmBulkBar(n)}</div><div class=crm-lh><label class=crm-inl><input type=checkbox id=crmsa onchange="crmSelAll(this.checked)" aria-label="Select all in this view"> <span id=crmlc>${L.length} contact${L.length===1?'':'s'}</span></label></div>
<div id=crmvl class=crm-vl role=list aria-label="Contacts"><div id=crmvs class=crm-vs style="height:${L.length*CRM_RH}px"></div></div>${L.length?'':'<p class="mut crm-ce">No contacts match. Clear the search or pick another view.</p>'}</div>${c?`<div class=crm-3w>${crm360(c,0)}</div>`:''}</div>`}
function crmBookUpd(){CRM.ui.list=crmBookList();CRM.ui.scroll=0;const vl=document.getElementById('crmvl');if(vl)vl.scrollTop=0;const lc=document.getElementById('crmlc');if(lc)lc.textContent=CRM.ui.list.length+' contact'+(CRM.ui.list.length===1?'':'s');crmListPaint()}
function crmListPaint(){const vl=document.getElementById('crmvl'),sp=document.getElementById('crmvs');if(!vl||!sp)return;const L=CRM.ui.list||[],H=CRM_RH,top=vl.scrollTop,h=vl.clientHeight||520,a=Math.max(0,Math.floor(top/H)-6),b=Math.min(L.length,Math.ceil((top+h)/H)+6);
 sp.style.height=L.length*H+'px';const tby=crmTasksBy(),sod=crmSOD();let s='';for(let i=a;i<b;i++)s+=crmRow(L[i],i,tby,sod);sp.innerHTML=s}
function crmRow(c,i,tby,sod){const t=(tby.get(c.id)||[])[0],on=CRM.ui.sel[c.id],cur=cid!=null&&+cid===c.id;
 return`<div class="crm-row ${cur?'cur':''} ${on?'sel':''}" style="top:${i*CRM_RH}px" role=listitem><input type=checkbox aria-label="Select ${esc(c.name)}" ${on?'checked':''} onchange="crmSelT(${c.id},this.checked)">
<button class=crm-rm onclick="crmOpen(${c.id})">${crmAv(c,32)}<span class=crm-rn><b>${esc(c.name)}</b><small>${esc(c.phone||c.email||'No phone')}${c.state?' &middot; '+esc(c.state):''}</small></span><span class=crm-rs>${crmStPill(c.stage)}<small class="${t&&t.due<sod?'neg':t&&t.due<sod+864e5?'crm-gold':''}">${t?esc(CRM_TY[t.ty]||'Task')+' '+crmWhen(t.due,t.ad):'No next step'}</small></span>${crmOwnAv(c.owner)}</button></div>`}
function crmSelT(id,on){if(on)CRM.ui.sel[id]=1;else delete CRM.ui.sel[id];crmBulkUpd()}
function crmSelAll(on){CRM.ui.sel={};if(on)(CRM.ui.list||[]).forEach(c=>CRM.ui.sel[c.id]=1);crmBulkUpd();crmListPaint()}
function crmBulkUpd(){const n=Object.keys(CRM.ui.sel).length,b=document.getElementById('crmbb');if(b){b.className='crm-bb'+(n?' on':'');b.innerHTML=crmBulkBar(n)}}
function crmBulkBar(n){if(!n)return'';const ags=crmAgents();return`<b>${n} selected</b>${crmOwnerView()?`<select aria-label="Assign selected" onchange="if(this.value)crmBulk('owner',this.value==='-'?'':this.value)"><option value="">Assign to</option>${ags.map(a=>`<option>${esc(a)}</option>`).join('')}<option value="-">Unassigned</option></select>`:`<button class="btn sm o" onclick="crmBulk('owner','${esc(WHO)}')">Claim</button>`}
<select aria-label="Move selected to stage" onchange="if(this.value)crmBulk('stage',this.value)"><option value="">Stage</option>${CRM_ST.map(s=>`<option value=${s}>${esc(CRM_SN[s])}</option>`).join('')}</select><select aria-label="Tag selected" onchange="if(this.value)crmBulk('tag',this.value)"><option value="">Add tag</option>${['Hot','Spouse','Spanish','Callback','Lapse risk','VIP'].map(t=>`<option>${t}</option>`).join('')}</select>
<button class="btn sm o" onclick="crmExport(1)">Export</button><button class="btn sm o" onclick="crmBulk('del')">Delete</button><button class="btn sm o" onclick="CRM.ui.sel={};crmBulkUpd();crmListPaint();const a=document.getElementById('crmsa');if(a)a.checked=false">Clear</button>`}
function crmBulk(k,v){const ids=Object.keys(CRM.ui.sel).map(Number).filter(id=>crmCan(crmGet(id)));if(!ids.length)return;const run=()=>{const tx=crmTx(()=>ids.forEach(id=>{const c=crmGet(id);if(!c)return;if(k==='owner'){crmPut(id,{owner:v});crmEv(id,'sys',{t:'Assigned to '+(v||'Unassigned'),noTouch:1})}else if(k==='stage')crmStage(id,v,'bulk move');else if(k==='tag'){if((c.tags||[]).indexOf(v)<0)crmPut(id,{tags:(c.tags||[]).concat([v])})}else if(k==='del')crmDel(id)}));
  CRM.ui.sel={};go();crmToast((k==='del'?'Deleted ':k==='owner'?'Assigned ':k==='stage'?'Moved ':'Tagged ')+ids.length+' contact'+(ids.length>1?'s':'')+'.',tx.undo)};if(k==='del')return ask('Delete '+ids.length+' contact'+(ids.length>1?'s':'')+'? You can undo right after.',run);run()}
function crmCsvCell(v){v=String(v==null?'':v);return/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function crmExport(sel){const ids=sel?Object.keys(CRM.ui.sel).map(Number):null,L=(ids&&ids.length?ids.map(crmGet).filter(Boolean):(CRM.ui.list||crmVisible()));const H=['Name','Phone','Email','Age','DOB','State','City','ZIP','Product','Source','Stage','Owner','Tags','Next action','Last touch'];
 const rows=[H].concat(L.map(c=>{const t=crmNext(c.id);return[c.name,c.phone,c.email,crmAgeOf(c),c.dob,c.state,c.city,c.zip,c.prod,c.src,CRM_SN[c.stage],c.owner,(c.tags||[]).join('; '),t?(CRM_TY[t.ty]||'')+' '+crmDay(t.due):'',c.lt?crmDay(c.lt):'']}));
 const csv=rows.map(r=>r.map(crmCsvCell).join(',')).join('\r\n'),fn='clients-'+crmToday()+'.csv';
 (async()=>{try{const d=globalThis.claude&&globalThis.claude.use?await globalThis.claude.use('downloads'):null;if(d&&d.save){await d.save({filename:fn,data:new Blob([csv],{type:'text/csv'})});return toast('Export ready: '+fn,1)}}catch(e){}
  try{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=fn;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);toast('Export ready: '+fn,1)}catch(e){toast('Export is not available here.')}})()}
/* ---------- Client 360 ---------- */
function crmEvIcon(ty){return{call:'&#9742;',text:'&#9993;',email:'@',meet:'&#9673;',note:'&#9998;',stage:'&#10148;',policy:'&#9733;',task:'&#10003;',sys:'&#8226;',import:'&#8681;'}[ty]||'&#8226;'}
function crmEvHtml(e){return`<div class="crm-ev t-${crmQS(e.ty)}"><i aria-hidden=true>${crmEvIcon(e.ty)}</i><div><small>${crmWhen(e.at)} &middot; ${esc(CRM_EVL[e.ty]||{stage:'Stage',policy:'Policy',task:'Task',sys:'System',import:'Import'}[e.ty]||e.ty)}${e.by?' &middot; '+esc(e.by):''}${e.o&&CRM_OUT[e.o]?` <span class=crm-pill>${esc(CRM_OUT[e.o])}</span>`:''}${(e.ty==='note'||CRM_EVL[e.ty])&&(e.by===WHO||crmOwnerView())?` <button class=x title="Delete" aria-label="Delete this entry" onclick="crmEvDel('${crmQS(e.id)}')">&times;</button>`:''}</small><p>${esc(e.t||'').replace(/\n/g,'<br>')}</p></div></div>`}
function crmEvDel(id){const e=CRM.e.get(id);if(!e)return;const tx=crmTx(()=>{const p='crme/'+crmEB(e.c,e.at),mt=crmMeta(p);crmW(p,{m:mt.m,b:mt.b,['e'+id]:{del:1}})});go();crmToast('Entry deleted.',tx.undo)}
function crmHistory(c){const h=CRM.hist[c.id];if(!CRM.db||(h&&Date.now()-h<6e4))return;CRM.hist[c.id]=Date.now();const bb=crmEBk(c.id);
 try{CRM.db.collection('crme').where('b','==',bb).get().then(s=>{let n=0;s.docs.forEach(d=>{const x=d.data()||{},p='crme/'+d.id;if(CRM.sv[p])return;CRM.sv[p]=x;n|=crmApply(p)});if(n)crmChanged(1)}).catch(()=>{})}catch(e){}}
function crm360(c,full){crmHistory(c);const t=crmNext(c.id),open=crmOpenTasks(c.id),ev=crmEvents(c.id),f=CRM.ui.evf||'all',win=crmWindow(c),pol=crmPolicies(c),age=crmAgeOf(c),ow=crmOwnerView(),ags=crmAgents();
 const fl={all:()=>true,call:e=>e.ty==='call'||e.ty==='meet',text:e=>e.ty==='text'||e.ty==='email',note:e=>e.ty==='note',policy:e=>e.ty==='policy',sys:e=>e.ty==='stage'||e.ty==='sys'||e.ty==='task'||e.ty==='import'}[f]||(()=>true),evs=ev.filter(fl).slice().reverse();
 const tags=(c.tags||[]).map(x=>`<span class=crm-tag>${esc(x)}<button aria-label="Remove tag ${esc(x)}" onclick="crmTagDel(${c.id},'${esc(String(x).replace(/'/g,''))}')">&times;</button></span>`).join('');
 const act=(href,lab,ic,on)=>href?`<a class=crm-act href="${esc(href)}" ${on?`onclick="${on}"`:''}><i aria-hidden=true>${ic}</i>${lab}</a>`:`<span class=crm-act aria-disabled=true><i aria-hidden=true>${ic}</i>${lab}</span>`;
 const btn=(on,lab,ic)=>`<button class=crm-act onclick="${on}"><i aria-hidden=true>${ic}</i>${lab}</button>`;
 const leadAge=c.rcv?crmAgo(c.rcv).replace(' ago',''):'';
 return`<div class="c crm-360" aria-label="Client record">${full||CRM.ui.back?`<button class="btn o sm crm-backb" onclick="crmBack()">&larr; Back</button>`:`<button class="x crm-cls" aria-label="Close record" onclick="crmBack()">&times;</button>`}
<div class=crm-3h>${crmAv(c,64)}<div class=crm-3n><h3>${esc(c.name)}</h3><small>${[age?age+' years':'',c.state?(CRM_STN[c.state]||c.state):'',c.prod,c.src,leadAge?'lead '+leadAge+' old':''].filter(Boolean).map(esc).join(' &middot; ')}</small>
<div class=crm-chips>${win.known?`<span class="crm-why ${win.ok?'crm-ok':'crm-bad'}" title="Client local time">${win.ok?'OK to call':'Outside calling hours'} &middot; ${win.label} local</span>`:''}${c.dnc?'<span class="crm-why crm-bad">DO NOT CONTACT</span>':''}${c.bad?'<span class="crm-why crm-bad">Bad number</span>':''}${c.sms?'<span class="crm-why crm-ok">Texts OK</span>':''}</div></div>
<div class=crm-3c><label>Stage<select onchange="crmStageSel(${c.id},this.value)" aria-label="Stage">${CRM_ST.map(s=>`<option value=${s} ${s===c.stage?'selected':''}>${esc(CRM_SN[s])}</option>`).join('')}</select></label>
<label>Owner${ow?`<select onchange="crmOwner(${c.id},this.value)" aria-label="Owner">${[['','Unassigned'],...ags.map(a=>[a,a]),...(c.owner&&ags.indexOf(c.owner)<0?[[c.owner,c.owner]]:[])].map(o=>`<option value="${esc(o[0])}" ${o[0]===(c.owner||'')?'selected':''}>${esc(o[1])}</option>`).join('')}</select>`:(!c.owner||c.owner==='Unassigned'?`<button class="btn sm" onclick="crmOwner(${c.id},WHO)">Claim this lead</button>`:`<b class=crm-ow>${esc(c.owner)}</b>`)}</label></div></div>
<div class=crm-tags>${tags}<input aria-label="Add a tag" placeholder="+ tag" list=crmtgl onkeydown="if(event.key==='Enter'&&this.value.trim()){crmTagAdd(${c.id},this.value.trim());this.value=''}"><datalist id=crmtgl>${['Hot','Spouse','Spanish','Callback','Lapse risk','VIP','Veteran'].map(x=>`<option>${x}</option>`).join('')}</datalist></div>
<div class=crm-acts>${act(crmTel(c),'Call','&#9742;',`crmCallTap(${c.id})`)}${act(crmSms(c,t),'Text','&#9993;',`crmTextTap(${c.id})`)}${act(crmMail(c),'Email','@','')}${btn(`crmSchedule(${c.id})`,'Schedule','&#9719;')}${btn(`crmLogPolicy(${c.id})`,'Log policy','&#9733;')}${btn(`mbOpen(${c.id})`,'Write message','&#9998;')}</div>
${CRM.ui.calling===c.id?crmOutBar(c):''}
<div class=crm-3g><div>
<div class="crm-na ${t?crmDueState(t):''}"><h4>Next action</h4>${t?`<div class=crm-nx data-t="${crmQS(t.id)}"><b>${esc(crmTL(t))}</b><small class="${crmDueState(t)==='over'?'neg':'crm-gold'}">${crmWhen(t.due,t.ad)}${t.ow&&t.ow!==WHO?' &middot; '+esc(t.ow):''}</small><div class=crm-row2><button class="btn sm" onclick="crmTDone('${crmQS(t.id)}')">Done</button><button class="btn sm o" onclick="crmSnoozeMenu('${crmQS(t.id)}')">Snooze</button><button class="btn sm o" onclick="crmTaskX('${crmQS(t.id)}')">Cancel task</button></div></div>${open.length>1?`<small>${open.length-1} more scheduled: ${open.slice(1,4).map(x=>esc(CRM_TY[x.ty]||'Task')+' '+crmWhen(x.due,x.ad)).join(', ')}</small>`:''}`:`<p class=mut>Nothing scheduled.</p><button class="btn sm" onclick="crmSchedule(${c.id})">Schedule the next step</button>`}</div>
<div class=crm-ql2><h4>Log what happened</h4><div class=crm-obg>${['na','vm','int','appt','cb','ni','bad'].map(o=>`<button class="crm-ob-b ${o==='int'?'crm-ok':o==='appt'?'crm-hi':''}" onclick="crmOut(${c.id},'${o}')">${esc(CRM_OUTS[o])}</button>`).join('')}</div>
<label for=crmnt class=crm-sr>Note type</label><div class=crm-row2><select id=crmnt aria-label="Type">${['note','call','text','email','meet'].map(k=>`<option value=${k}>${CRM_EVL[k]}</option>`).join('')}</select></div><label for=crmnx class=crm-sr>Note</label><textarea id=crmnx rows=2 placeholder="What was discussed? Family, health, budget, objections, next steps"></textarea><button class="btn sm" onclick="crmNoteSave(${c.id})">Save note</button></div>
<h4>Timeline</h4><div class=crm-evf role=tablist aria-label="Filter timeline">${[['all','All'],['call','Calls'],['text','Texts'],['note','Notes'],['policy','Policies'],['sys','System']].map(x=>`<button class="chip ${f===x[0]?'on':''}" onclick="CRM.ui.evf='${x[0]}';go()">${x[1]}</button>`).join('')}</div>
<div class=crm-tl>${evs.length?evs.slice(0,CRM.ui.evmore||60).map(crmEvHtml).join(''):'<p class=mut>Nothing logged yet.</p>'}${evs.length>(CRM.ui.evmore||60)?`<button class="btn o sm" onclick="CRM.ui.evmore=${(CRM.ui.evmore||60)+60};go()">Show older</button>`:''}</div></div>
<div><div class=crm-box><h4>Policies</h4>${pol.length?pol.map(p=>{const ms=Math.floor((Date.now()-Date.parse(p.d+'T12:00:00'))/(30.44*864e5)),risk=(p.st==='Issued'||p.st==='Paid')&&ms<12?12-ms:0;return`<div class=crm-pol><b>${esc(p.car||'')} &middot; ${esc(p.prod||'')}</b><small>${esc(p.d)} &middot; $${Math.round(+p.ap||0).toLocaleString()} AP &middot; <span class="crm-pill ${p.st==='Chargeback'||p.st==='Declined'?'bad':''}">${esc(p.st)}</span></small>${risk?`<small class=crm-gold>${risk} month${risk>1?'s':''} of advance still at risk: keep the draft healthy.</small>`:''}${p.st==='Chargeback'?'<small class=neg>Chargeback: call to save the policy.</small>':''}</div>`}).join(''):'<p class=mut>No policies yet.</p>'}<button class="btn sm" onclick="crmLogPolicy(${c.id})">+ Log policy</button></div>
<div class=crm-box><h4>Profile</h4>${crmProfile(c)}<small id=crmps class=crm-ps aria-live=polite>Changes save as you go and are shared with your team.</small></div>
<div class=crm-box><h4>Compliance</h4><label class=crm-inl><input type=checkbox ${c.dnc?'checked':''} onchange="crmDnc(${c.id},this.checked)"> Do not contact</label><label class=crm-inl><input type=checkbox ${c.sms?'checked':''} onchange="crmField(${c.id},'sms',this.checked?Date.now():0)"> Consent to text${c.sms>1?' ('+crmDay(c.sms)+')':''}</label><label for=crmcmp>Compliance notes</label><textarea id=crmcmp rows=2 onchange="crmField(${c.id},'comp',this.value)" placeholder="Consent source, recordings, requests">${esc(c.comp||'')}</textarea></div>
<div class=crm-box><h4>Referrals</h4><label for=crmrfb>Referred by</label><input id=crmrfb value="${esc((c.ref||{}).by||'')}" onchange="crmField(${c.id},'ref.by',this.value)"><label for=crmrfg>Referrals given</label><input id=crmrfg type=number min=0 value="${esc((c.ref||{}).given||'')}" onchange="crmField(${c.id},'ref.given',+this.value||0)"><button class="btn sm o" onclick="crmRefAsk(${c.id})">${(c.ref||{}).asked?'Asked '+crmDay((c.ref||{}).asked)+' &middot; ask again':'Mark referral ask done'}</button></div>
<button class="btn o sm crm-del" onclick="crmDelAsk(${c.id})">Delete contact</button></div></div></div>`}
function crmProfile(c){const v=k=>k.indexOf('.')>0?((c[k.split('.')[0]]||{})[k.split('.')[1]]||''):(k==='age'?crmAgeOf(c):(c[k]||''));
 const F=[['Personal',[['name','Full name','text'],['dob','Date of birth','date'],['age','Age','ro'],['info.marital','Marital status','sel',['','Single','Married','Divorced','Widowed']],['info.occ','Occupation','text'],['info.tobacco','Tobacco use','sel',['','No','Yes']]]],
 ['Contact',[['phone','Phone','tel'],['phone2','Alternate phone','tel'],['email','Email','email'],['street','Street address','text'],['city','City','text'],['state','State','text'],['zip','ZIP code','text'],['info.pref','Preferred contact','sel',['','Call','Text','Email']],['info.best','Best time to reach','sel',['','Mornings','Afternoons','Evenings']]]],
 ['Beneficiary and emergency contact',[['info.bname','Beneficiary name','text'],['info.brel','Relationship','text'],['info.bphone','Beneficiary phone','tel'],['info.ename','Emergency contact','text'],['info.ephone','Emergency phone','tel']]],
 ['Needs',[['info.goal','Coverage goal','text'],['info.budget','Monthly budget','text'],['info.house','Household and dependents','text'],['ap','Expected annual premium ($)','number'],['prod','Product interest','sel',['',...CRM_PROD]],['info.health','Health notes','area']]],
 ['Lead info',[['src','Lead source','text'],['ven','Vendor','text'],['cost','Lead cost ($)','number'],['rcvd','Received','ro2']]]];
 const fld=([k,l,t,o])=>{const id='crmf_'+k.replace('.','_'),val=k==='rcvd'?(c.rcv?new Date(c.rcv).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):''):v(k);
  if(t==='ro'||t==='ro2')return`<div><label for=${id}>${l}</label><input id=${id} value="${esc(val)}" readonly tabindex=-1></div>`;
  if(t==='sel')return`<div><label for=${id}>${l}</label><select id=${id} onchange="crmField(${c.id},'${k}',this.value)">${o.map(x=>`<option value="${esc(x)}" ${x===val||(k==='info.best'&&x&&String(val).toLowerCase().indexOf(x.toLowerCase().slice(0,4))===0)?'selected':''}>${esc(x||'Not set')}</option>`).join('')}</select></div>`;
  if(t==='area')return`<div class=crm-full><label for=${id}>${l}</label><textarea id=${id} rows=2 onchange="crmField(${c.id},'${k}',this.value)">${esc(val)}</textarea></div>`;
  return`<div><label for=${id}>${l}</label><input id=${id} type=${t} value="${esc(val)}" onchange="crmField(${c.id},'${k}',this.value)"></div>`};
 return F.map(([g,fs],i)=>`<details class=crm-pd ${i<2?'open':''}><summary>${g}</summary><div class=cig>${fs.map(fld).join('')}</div></details>`).join('')}
function crmField(id,k,v){const c=crmGet(id);if(!c)return;if(typeof v==='string')v=v.trim();let patch={};
 if(k==='name'){if(!v)return toast('Name cannot be empty.');if(v!==c.name){const old=String(c.name).toLowerCase();(D.policies||[]).forEach(p=>{if(String(p.cl).toLowerCase()===old&&(p.crmId==null||+p.crmId===+id)){p.cl=v;p.crmId=id}});try{save()}catch(e){}}patch.name=v}
 else if(k==='phone'||k==='phone2')patch[k]=crmFmtPhone(v)||v;else if(k==='state')patch.state=crmStateCode(v)||v;else if(k==='dob'){patch.dob=v;const a=crmAgeOf({dob:v});if(a)patch.age=String(a)}else if(k==='cost'||k==='ap')patch[k]=+v||0;
 else if(k.indexOf('.')>0){const [a,b]=k.split('.');patch[a]={[b]:v}}else patch[k]=v;
 crmPut(id,patch);const s=document.getElementById('crmps');if(s)s.textContent='Saved';if(k==='dob'){const e=document.getElementById('crmf_age');if(e)e.value=crmAgeOf(crmGet(id))||''}}
function crmOwner(id,v){const c=crmGet(id);if(!c)return;const tx=crmTx(()=>{crmPut(id,{owner:v});crmEv(id,'sys',{t:(v===WHO&&!crmOwnerView()?'Claimed by ':'Assigned to ')+(v||'Unassigned'),noTouch:1});crmOpenTasks(id).forEach(t=>crmTaskPatch(t.id,{ow:v}))});go();crmToast((v?'Owner: '+v:'Unassigned')+'.',tx.undo)}
function crmTagAdd(id,v){const c=crmGet(id);if(!c||(c.tags||[]).indexOf(v)>=0)return;crmPut(id,{tags:(c.tags||[]).concat([v.slice(0,24)])});CRM.ui.focus='';go()}
function crmTagDel(id,v){const c=crmGet(id);if(!c)return;crmPut(id,{tags:(c.tags||[]).filter(x=>x!==v)});go()}
function crmDnc(id,on){if(on)return ask('Mark as Do Not Contact? Open follow-ups are cancelled and calling is blocked.',()=>{const tx=crmTx(()=>crmOutcome(id,'dnc',{ty:'note',t:'Marked Do Not Contact'}));go();crmToast('Marked Do Not Contact.',tx.undo)});crmPut(id,{dnc:0});crmEv(id,'sys',{t:'Do Not Contact removed',noTouch:1});go()}
function crmRefAsk(id){crmPut(id,{ref:{asked:Date.now()}});crmEv(id,'note',{t:'Asked for referrals'});go();toast('Referral ask logged',1)}
function crmNoteSave(id){const x=document.getElementById('crmnx'),ty=(document.getElementById('crmnt')||{}).value||'note';if(!x||!x.value.trim())return toast('Type a note first.');crmEv(id,ty,{t:x.value.trim()});x.value='';go();toast('Saved to the timeline',1)}
function crmTaskX(tid){const tx=crmTx(()=>crmTaskPatch(tid,{s:'x',dn:Date.now(),dby:WHO}));go();crmToast('Task cancelled.',tx.undo)}
function crmDelAsk(id){const c=crmGet(id);if(!c)return;ask('Delete '+esc(c.name)+'? Their history stays recoverable with Undo.',()=>{const tx=crmTx(()=>crmDel(id));cid=null;go();crmToast(c.name+' deleted.',tx.undo)})}
function crmLogPolicy(id){const c=crmGet(id);if(!c)return;CRM.ui.polFor=id;openM('P');const set=(i,v)=>{const e=document.getElementById(i);if(e&&v){if(e.tagName==='SELECT'){if([...e.options].some(o=>o.value===v||o.text===v))e.value=v}else e.value=v}};set('pc',c.name);set('pg',c.owner);set('psr',c.src);set('pp',c.prod==='Mortgage Protection'?'Term':c.prod);set('ps','Submitted');if(c.ap)set('pa',String(c.ap))}
/* ---------- legacy write paths routed here (see INTEGRATION.md) ---------- */
function crmSaveC(id){const v=n=>(document.getElementById(n)||{value:''}).value.trim();if(!v('cn1'))return toast('Enter a name.');const o={name:v('cn1'),phone:crmFmtPhone(v('cp'))||v('cp'),email:v('ce'),age:v('ca'),src:v('cs')},fu=v('cf'),st=v('cst');
 if(id){const c=crmGet(id);if(!c)return closeM();crmPut(id,o);if(st&&CRM_N2L[c.stage]!==st)crmStage(id,CRM_L2N[st]||'new','edited');crmSetFuDate(id,fu);closeM();go();return}
 const d=crmFindDup(o,crmDupIndex(crmAll()));const make=()=>{const c=crmCreate(Object.assign(o,{stage:CRM_L2N[st]||'new'}),{noTask:!!fu});if(fu)crmSetFuDate(c.id,fu);cid=c.id;closeM();go()};
 if(d)return ask('This looks like a duplicate of '+esc(d.c.name)+' ('+esc(d.why)+'). Add anyway?',make);make()}
function crmSetFuDate(id,fu){const cur=crmOpenTasks(id).filter(t=>t.ty==='fu'||t.r==='legacy');if(!fu){cur.forEach(t=>crmTaskPatch(t.id,{s:'d',dn:Date.now(),dby:WHO}));return}if(cur.some(t=>crmDay(t.due)===fu))return;cur.forEach(t=>crmTaskPatch(t.id,{s:'x',dn:Date.now()}));const c=crmGet(id);crmTask({id:'fu_'+id+'_'+fu.replace(/-/g,''),c:id,ty:'fu',t:'Follow-up',due:crmAt(fu,9,0),ad:1,ow:c?c.owner:WHO,r:'man'})}
function crmAddN(id){const x=document.getElementById('nx'),ty=(document.getElementById('nt')||{}).value||'Note';if(!x||!x.value.trim())return toast('Type a note first.');crmEv(id,{Call:'call',Text:'text',Email:'email',Meeting:'meet',Note:'note'}[ty]||'note',{t:x.value.trim()});go()}
function crmSetSt(id,v){const c=crmGet(id);if(c&&CRM_N2L[c.stage]!==v)crmStage(id,CRM_L2N[v]||'new','legacy select');go()}
function crmDelN(id,i){const n=(crmMy().find(x=>x.id==id)||{notes:[]}).notes[i];if(n&&n._e)crmEvDel(n._e);else go()}
function crmDelC(id){crmDelAsk(id)}
function crmClearFu(id){const t=crmNext(id);if(t){crmDone(t.id)}go();toast('Follow-up cleared',1)}
function crmCiSet(id,k,v){const map={marital:'info.marital',occ:'info.occ',tobacco:'info.tobacco',pref:'info.pref',best:'info.best',bname:'info.bname',brel:'info.brel',bphone:'info.bphone',ename:'info.ename',ephone:'info.ephone'};crmField(id,map[k]||k,String(v))}
function crmMbPin(c,fresh){if(!c)return;const cur=(crmGet(c.id)||{}).mb||{};if(!fresh&&cur.pin)return;const pin=String(Math.floor(1000+Math.random()*9000));crmPut(c.id,{mb:{pin}});c.mb=Object.assign({},c.mb||{},{pin});if(fresh){const e=document.getElementById('mbf_pin');if(e)e.value=pin;mbUpdate()}}
function crmMbSet(k,v){const c=mbClient();if(!c)return;c.mb=c.mb||{};if(v==='')delete c.mb[k];else c.mb[k]=v;crmPut(c.id,{mb:{[k]:v===''?null:v}});
 if(k==='initial'){const r=document.getElementById('mbf_recurring');if(r&&c.mb.recurring===undefined)r.value=mbVal(c,'recurring')}mbUpdate()}
function crmMbLog(){const c=mbClient(),o=document.getElementById('mbo');if(!c||!o||!o.value.trim())return toast('Choose a client and write a message first.');const k=document.getElementById('mbk');crmEv(c.id,{Text:'text',Email:'email',Note:'note'}[(k&&k.value)||'Text']||'text',{t:'Message sent:\n'+o.value});toast('Saved to '+c.name+"'s timeline",1)}
function crmSimLead(){const pk=a=>a[Math.floor(Math.random()*a.length)],ri=(a,b)=>a+Math.floor(Math.random()*(b-a+1)),name=pk(SFN)+' '+pk(SLN),s=pk(CRM_SRC.slice(0,4)),st=pk(['PA','OH','WV','NY','FL']);
 const c=crmCreate({name,phone:'412-555-'+ri(1000,9999),email:name.toLowerCase().replace(' ','.')+'@example.com',age:String(ri(38,74)),state:st,prod:pk(['Final Expense','Mortgage Protection','Term']),src:s,owner:WHO},{note:'Inbound lead from '+s+'. Call within five minutes.'});
 pushAlert({k:'crmn-'+c.id,sev:'info',t:'New lead',m:`${name} from ${s} needs a first call`,go:['Clients','',c.id]})}
function crmCmds(L){if(!crmOn())return;L.push(['New lead','Clients',()=>crmNewLead()],['Open Today','Clients',()=>{cid=null;openTab('Clients','Today')}],['Call next lead','Clients',crmCallNext],['Open pipeline','Clients',()=>{cid=null;openTab('Clients','Pipeline')}],['Import leads','Clients',()=>{cid=null;openTab('Clients','Today');crmImport()}])}
(function(){try{const s=document.createElement('style');s.id='crmcss';s.textContent=CRM_CSS;(document.body||document.head).appendChild(s)}catch(e){}})();
/*CRMend*/
