from playwright.sync_api import sync_playwright
F='file:///mnt/user-data/outputs/owq-command-station-v2.html'
def login(pg,card,pin=None):
    import lgx
    pg.evaluate("lockView()");pg.wait_for_timeout(1200)
    lgx.login(pg,card);pg.wait_for_timeout(5000)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path='/opt/pw-browsers/chromium',args=['--no-sandbox','--disable-webgl'])
    ctx=b.new_context(viewport={'width':1366,'height':860});ctx.add_init_script("try{localStorage.setItem('owq_gq','still')}catch(e){}");pg=ctx.new_page();errs=[];pg.on('pageerror',lambda e:errs.append('PE '+str(e)[:300]))
    pg.goto(F);pg.wait_for_timeout(2500)
    login(pg,1)
    print('agent',pg.evaluate("[WHO,ONLINE,LNM.length,LNM.filter(m=>m.tr===1).length]"))
    pg.evaluate("openTab('Learning Network')");pg.wait_for_timeout(800);pg.screenshot(path='bp_1.png')
    pg.evaluate("lnTrk(1)");pg.wait_for_timeout(800);pg.screenshot(path='bp_2.png')
    print('gate1',pg.evaluate("(document.querySelector('.lngt')||{}).innerText"))
    pg.evaluate("""LNM.filter(m=>!m.tr&&!m.auto).forEach(m=>{if(!lnRec(WHO,m.id))D.learn.push({_i:'ln_t_'+m.id,_t:Date.now()*1000,u:WHO,m:m.id,sc:4,n:4,xp:150,ts:Date.now()})});save();lnR()""")
    pg.wait_for_timeout(600);pg.screenshot(path='bp_3.png')
    print('gate2',pg.evaluate("(document.querySelector('.lngt')||{}).innerText"))
    pg.evaluate("lnReqSend()");pg.wait_for_timeout(800);pg.screenshot(path='bp_4.png')
    print('req',pg.evaluate("JSON.stringify(D.lnreq)"))
    login(pg,6)
    pg.wait_for_timeout(6500)
    print('owner',pg.evaluate("[WHO,lnOwner(),AL().filter(a=>/Blueprint/.test(a.t)).map(a=>a.t+': '+a.m)]"))
    pg.evaluate("openTab('Learning Network')");pg.wait_for_timeout(800);pg.screenshot(path='bp_5.png')
    print('panel',pg.evaluate("(document.querySelector('.lnrq')||{}).innerText"))
    pg.evaluate("lnReqSet('Nate Johnson','approved')");pg.wait_for_timeout(600)
    print('after approve',pg.evaluate("JSON.stringify(D.lnreq)"))
    login(pg,1);pg.wait_for_timeout(6500)
    print('agent alerts',pg.evaluate("AL().filter(a=>/Blueprint/.test(a.t)).map(a=>a.t)"))
    pg.evaluate("LN.trk=null;openTab('Learning Network')");pg.wait_for_timeout(900);pg.screenshot(path='bp_6.png')
    print('open',pg.evaluate("[LN.trk,lnBpOpen(WHO,lnStates(WHO)),document.querySelectorAll('.lnn.soon').length,(document.querySelector('.lnh')||{}).innerText]"))
    pg.evaluate("lnOpen('bp-code-of-conduct')");pg.wait_for_timeout(700);pg.screenshot(path='bp_7.png')
    print('nav',pg.evaluate("[...document.querySelectorAll('.nsubs .nsb')].slice(0,6).map(e=>e.innerText)"))
    print(errs[:5] or 'no page errors')
    b.close()
